/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JToolBar;

/**
 *
 * @author Dyl
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        tlBarOpciones = new javax.swing.JToolBar();
        btnAgVehiculo = new javax.swing.JButton();
        btnAgPropietarios = new javax.swing.JButton();
        btnAgFormulario = new javax.swing.JButton();
        btnConsulRecaudo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        tlBarAvisos = new javax.swing.JToolBar();
        Aviso = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        MenuAgregar = new javax.swing.JMenu();
        btnMnAgVehiculo = new javax.swing.JMenuItem();
        btnMnAgPropietario = new javax.swing.JMenuItem();
        btnMnAgFormulario = new javax.swing.JMenuItem();
        MenuConsultar = new javax.swing.JMenu();
        btnMnConsulVehiculos = new javax.swing.JMenuItem();
        btnMnConsulPropietarios = new javax.swing.JMenuItem();
        btnMnConsulFormularios = new javax.swing.JMenuItem();
        MenuAyuda = new javax.swing.JMenu();
        btnMnAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto Formulario");
        setMinimumSize(new java.awt.Dimension(1100, 700));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        tlBarOpciones.setOrientation(javax.swing.SwingConstants.VERTICAL);
        tlBarOpciones.setRollover(true);

        btnAgVehiculo.setText("Vehiculo");
        btnAgVehiculo.setFocusable(false);
        btnAgVehiculo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgVehiculo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlBarOpciones.add(btnAgVehiculo);

        btnAgPropietarios.setText("Propietario");
        btnAgPropietarios.setFocusable(false);
        btnAgPropietarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgPropietarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlBarOpciones.add(btnAgPropietarios);

        btnAgFormulario.setText("Formulario");
        btnAgFormulario.setFocusable(false);
        btnAgFormulario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgFormulario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlBarOpciones.add(btnAgFormulario);

        btnConsulRecaudo.setText("Consultar Recaudo");
        btnConsulRecaudo.setFocusable(false);
        btnConsulRecaudo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsulRecaudo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlBarOpciones.add(btnConsulRecaudo);

        btnSalir.setText("Salir");
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        tlBarOpciones.add(btnSalir);

        tlBarAvisos.setRollover(true);
        tlBarAvisos.add(Aviso);

        MenuAgregar.setMnemonic('e');
        MenuAgregar.setText("Agregar");

        btnMnAgVehiculo.setText("Vehiculo");
        MenuAgregar.add(btnMnAgVehiculo);

        btnMnAgPropietario.setText("Propietario");
        MenuAgregar.add(btnMnAgPropietario);

        btnMnAgFormulario.setText("Formulario");
        MenuAgregar.add(btnMnAgFormulario);

        menuBar.add(MenuAgregar);

        MenuConsultar.setText("Consultar");

        btnMnConsulVehiculos.setText("Vehiculos");
        MenuConsultar.add(btnMnConsulVehiculos);

        btnMnConsulPropietarios.setText("Propietarios");
        MenuConsultar.add(btnMnConsulPropietarios);

        btnMnConsulFormularios.setText("Recaudo Formularios");
        MenuConsultar.add(btnMnConsulFormularios);

        menuBar.add(MenuConsultar);

        MenuAyuda.setMnemonic('h');
        MenuAyuda.setText("Ayuda");

        btnMnAcercaDe.setMnemonic('a');
        btnMnAcercaDe.setText("Acerca de");
        MenuAyuda.add(btnMnAcercaDe);

        menuBar.add(MenuAyuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tlBarOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Escritorio))
                    .addComponent(tlBarAvisos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tlBarOpciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Escritorio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tlBarAvisos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     *
     * @return
     */
    public JLabel getAviso() {
        return Aviso;
    }

    /**
     *
     * @param Aviso
     */
    public void setAviso(JLabel Aviso) {
        this.Aviso = Aviso;
    }

    /**
     *
     * @return
     */
    public JDesktopPane getEscritorio() {
        return Escritorio;
    }

    /**
     *
     * @param Escritorio
     */
    public void setEscritorio(JDesktopPane Escritorio) {
        this.Escritorio = Escritorio;
    }

    /**
     *
     * @return
     */
    public JMenu getMenuAgregar() {
        return MenuAgregar;
    }

    /**
     *
     * @param MenuAgregar
     */
    public void setMenuAgregar(JMenu MenuAgregar) {
        this.MenuAgregar = MenuAgregar;
    }

    /**
     *
     * @return
     */
    public JMenu getMenuAyuda() {
        return MenuAyuda;
    }

    /**
     *
     * @param MenuAyuda
     */
    public void setMenuAyuda(JMenu MenuAyuda) {
        this.MenuAyuda = MenuAyuda;
    }

    /**
     *
     * @return
     */
    public JMenu getMenuConsultar() {
        return MenuConsultar;
    }

    /**
     *
     * @param MenuConsultar
     */
    public void setMenuConsultar(JMenu MenuConsultar) {
        this.MenuConsultar = MenuConsultar;
    }

    /**
     *
     * @return
     */
    public JButton getBtnAgFormulario() {
        return btnAgFormulario;
    }

    /**
     *
     * @param btnAgFormulario
     */
    public void setBtnAgFormulario(JButton btnAgFormulario) {
        this.btnAgFormulario = btnAgFormulario;
    }

    /**
     *
     * @return
     */
    public JButton getBtnAgPropietarios() {
        return btnAgPropietarios;
    }

    /**
     *
     * @param btnAgPropietarios
     */
    public void setBtnAgPropietarios(JButton btnAgPropietarios) {
        this.btnAgPropietarios = btnAgPropietarios;
    }

    /**
     *
     * @return
     */
    public JButton getBtnAgVehiculo() {
        return btnAgVehiculo;
    }

    /**
     *
     * @param btnAgVehiculo
     */
    public void setBtnAgVehiculo(JButton btnAgVehiculo) {
        this.btnAgVehiculo = btnAgVehiculo;
    }

    /**
     *
     * @return
     */
    public JButton getBtnConsulRecaudo() {
        return btnConsulRecaudo;
    }

    /**
     *
     * @param btnConsulRecaudo
     */
    public void setBtnConsulRecaudo(JButton btnConsulRecaudo) {
        this.btnConsulRecaudo = btnConsulRecaudo;
    }

    /**
     *
     * @return
     */
    public JMenuItem getBtnMnAcercaDe() {
        return btnMnAcercaDe;
    }

    /**
     *
     * @param btnMnAcercaDe
     */
    public void setBtnMnAcercaDe(JMenuItem btnMnAcercaDe) {
        this.btnMnAcercaDe = btnMnAcercaDe;
    }

    /**
     *
     * @return
     */
    public JMenuItem getBtnMnAgFormulario() {
        return btnMnAgFormulario;
    }

    /**
     *
     * @param btnMnAgFormulario
     */
    public void setBtnMnAgFormulario(JMenuItem btnMnAgFormulario) {
        this.btnMnAgFormulario = btnMnAgFormulario;
    }

    /**
     *
     * @return
     */
    public JMenuItem getBtnMnAgPropietario() {
        return btnMnAgPropietario;
    }

    /**
     *
     * @param btnMnAgPropietario
     */
    public void setBtnMnAgPropietario(JMenuItem btnMnAgPropietario) {
        this.btnMnAgPropietario = btnMnAgPropietario;
    }

    /**
     *
     * @return
     */
    public JMenuItem getBtnMnAgVehiculo() {
        return btnMnAgVehiculo;
    }

    /**
     *
     * @param btnMnAgVehiculo
     */
    public void setBtnMnAgVehiculo(JMenuItem btnMnAgVehiculo) {
        this.btnMnAgVehiculo = btnMnAgVehiculo;
    }

    /**
     *
     * @return
     */
    public JMenuItem getBtnMnConsulFormularios() {
        return btnMnConsulFormularios;
    }

    /**
     *
     * @param btnMnConsulFormularios
     */
    public void setBtnMnConsulFormularios(JMenuItem btnMnConsulFormularios) {
        this.btnMnConsulFormularios = btnMnConsulFormularios;
    }

    /**
     *
     * @return
     */
    public JMenuItem getBtnMnConsulPropietarios() {
        return btnMnConsulPropietarios;
    }

    /**
     *
     * @param btnMnConsulPropietarios
     */
    public void setBtnMnConsulPropietarios(JMenuItem btnMnConsulPropietarios) {
        this.btnMnConsulPropietarios = btnMnConsulPropietarios;
    }

    /**
     *
     * @return
     */
    public JMenuItem getBtnMnConsulVehiculos() {
        return btnMnConsulVehiculos;
    }

    /**
     *
     * @param btnMnConsulVehiculos
     */
    public void setBtnMnConsulVehiculos(JMenuItem btnMnConsulVehiculos) {
        this.btnMnConsulVehiculos = btnMnConsulVehiculos;
    }

    /**
     *
     * @return
     */
    public JButton getBtnSalir() {
        return btnSalir;
    }

    /**
     *
     * @param btnSalir
     */
    public void setBtnSalir(JButton btnSalir) {
        this.btnSalir = btnSalir;
    }

    /**
     *
     * @param menuBar
     */
    public void setMenuBar(JMenuBar menuBar) {
        this.menuBar = menuBar;
    }

    /**
     *
     * @return
     */
    public JToolBar getTlBarAvisos() {
        return tlBarAvisos;
    }

    /**
     *
     * @param tlBarAvisos
     */
    public void setTlBarAvisos(JToolBar tlBarAvisos) {
        this.tlBarAvisos = tlBarAvisos;
    }

    /**
     *
     * @return
     */
    public JToolBar getTlBarOpciones() {
        return tlBarOpciones;
    }

    /**
     *
     * @param tlBarOpciones
     */
    public void setTlBarOpciones(JToolBar tlBarOpciones) {
        this.tlBarOpciones = tlBarOpciones;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aviso;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu MenuAgregar;
    private javax.swing.JMenu MenuAyuda;
    private javax.swing.JMenu MenuConsultar;
    private javax.swing.JButton btnAgFormulario;
    private javax.swing.JButton btnAgPropietarios;
    private javax.swing.JButton btnAgVehiculo;
    private javax.swing.JButton btnConsulRecaudo;
    private javax.swing.JMenuItem btnMnAcercaDe;
    private javax.swing.JMenuItem btnMnAgFormulario;
    private javax.swing.JMenuItem btnMnAgPropietario;
    private javax.swing.JMenuItem btnMnAgVehiculo;
    private javax.swing.JMenuItem btnMnConsulFormularios;
    private javax.swing.JMenuItem btnMnConsulPropietarios;
    private javax.swing.JMenuItem btnMnConsulVehiculos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JToolBar tlBarAvisos;
    private javax.swing.JToolBar tlBarOpciones;
    // End of variables declaration//GEN-END:variables

}
