/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.JToolBar;

/**
 *
 * @author estudiante
 */
public class FrmRegistro extends javax.swing.JFrame {

    /**
     * Creates new form frmVentana
     */
    public FrmRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPaneRecaudo = new javax.swing.JTabbedPane();
        pnlProp = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblCalidad = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblMunicipio = new javax.swing.JLabel();
        lblFecNac = new javax.swing.JLabel();
        lblPropiedad = new javax.swing.JLabel();
        lblTblContribuyentes = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtCalidad = new javax.swing.JTextField();
        cmbTipoDocu = new javax.swing.JComboBox<>();
        txtCedula = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtMunicipio = new javax.swing.JTextField();
        txtFecNac = new javax.swing.JTextField();
        txtPropiedad = new javax.swing.JTextField();
        btnRegistrarProp = new javax.swing.JButton();
        scrollTblDatosContribuyentes = new javax.swing.JScrollPane();
        tblDatosContibuyentes = new javax.swing.JTable();
        pnlVehiculo = new javax.swing.JPanel();
        txtPlaca = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        txtCilindraje = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        lblPlaca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblCilindraje = new javax.swing.JLabel();
        lblCombustible = new javax.swing.JLabel();
        txtCanPas = new javax.swing.JTextField();
        cmbVehiculo = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        lblCantPas = new javax.swing.JLabel();
        lblTblDatosVehiculo = new javax.swing.JLabel();
        scrollTblDatosVehiculo = new javax.swing.JScrollPane();
        tblDatosVehiculo = new javax.swing.JTable();
        btnCambiarVehiculo = new javax.swing.JButton();
        lblTipo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtCombustible = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        pnlRecaudo = new javax.swing.JPanel();
        scrollTblVehiRecaudo = new javax.swing.JScrollPane();
        tblDatosVehiRecaudo = new javax.swing.JTable();
        btnRecaudo = new javax.swing.JButton();
        txtRecaudo = new javax.swing.JTextField();
        lblRecaudoTotal = new javax.swing.JLabel();
        cmbNFormulario = new javax.swing.JComboBox<>();
        scrollTblDatosContRecaudo = new javax.swing.JScrollPane();
        tblDatosContRecaudo = new javax.swing.JTable();
        NFormulario = new javax.swing.JLabel();
        lblTblVehiRecaudo = new javax.swing.JLabel();
        lblTblContRecaudo = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        tbAvisos = new javax.swing.JToolBar();
        lbAvisos = new javax.swing.JLabel();
        btnAnadirFormulario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro Impuesto Vehiculo");
        setBackground(new java.awt.Color(153, 204, 0));
        setResizable(false);

        tabPaneRecaudo.setBackground(new java.awt.Color(255, 255, 153));
        tabPaneRecaudo.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        tabPaneRecaudo.setMinimumSize(new java.awt.Dimension(122, 50));

        pnlProp.setBackground(new java.awt.Color(204, 204, 255));

        lblNombre.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblNombre.setText("Nombre");

        lblCalidad.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblCalidad.setText("Calidad sobre Vehiculo");

        lblCedula.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblCedula.setText("Tipo de Documento");

        lblDireccion.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblDireccion.setText("Direccion");

        lblCorreo.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblCorreo.setText("Correo");

        lblMunicipio.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblMunicipio.setText("Municipio");

        lblFecNac.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblFecNac.setText("Fecha de Nacimiento");

        lblPropiedad.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblPropiedad.setText("Porcentaje de Propiedad");

        lblTblContribuyentes.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblTblContribuyentes.setText("CONTRIBUYENTES");

        txtNom.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtNom.setName("Nombre De Propietario"); // NOI18N
        txtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomActionPerformed(evt);
            }
        });

        txtCalidad.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtCalidad.setName("Calidad del Propietario Sobre Vehiculo"); // NOI18N

        cmbTipoDocu.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        cmbTipoDocu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", "TI", "TE" }));

        txtCedula.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtCedula.setName("Numero De Documento"); // NOI18N
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        txtDireccion.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtDireccion.setName("Direccion Del Propietario"); // NOI18N

        txtCorreo.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtCorreo.setName("Correo Del Propietario"); // NOI18N
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        txtMunicipio.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtMunicipio.setName("Municipio Del Propietario"); // NOI18N

        txtFecNac.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtFecNac.setName("Fecha de Nacimiento Del Propietario"); // NOI18N
        txtFecNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFecNacActionPerformed(evt);
            }
        });

        txtPropiedad.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtPropiedad.setName("Procentaje De Propiedad Del Propietario Sobre El Vehiculo"); // NOI18N
        txtPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPropiedadActionPerformed(evt);
            }
        });

        btnRegistrarProp.setBackground(new java.awt.Color(255, 255, 204));
        btnRegistrarProp.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnRegistrarProp.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarProp.setText("REGISTRAR");
        btnRegistrarProp.setToolTipText("");
        btnRegistrarProp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrarProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPropActionPerformed(evt);
            }
        });

        tblDatosContibuyentes.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tblDatosContibuyentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Documento", "Correo", "Edad", "Calidad", "Direccion", "Municipio", "% Propiedad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDatosContibuyentes.setEnabled(false);
        scrollTblDatosContribuyentes.setViewportView(tblDatosContibuyentes);

        javax.swing.GroupLayout pnlPropLayout = new javax.swing.GroupLayout(pnlProp);
        pnlProp.setLayout(pnlPropLayout);
        pnlPropLayout.setHorizontalGroup(
            pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPropLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPropLayout.createSequentialGroup()
                        .addComponent(lblTblContribuyentes)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPropLayout.createSequentialGroup()
                        .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scrollTblDatosContribuyentes)
                            .addGroup(pnlPropLayout.createSequentialGroup()
                                .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNom)
                                    .addComponent(lblFecNac)
                                    .addComponent(lblCorreo)
                                    .addComponent(lblCedula)
                                    .addComponent(txtCorreo)
                                    .addComponent(lblNombre)
                                    .addGroup(pnlPropLayout.createSequentialGroup()
                                        .addComponent(cmbTipoDocu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtFecNac))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCalidad)
                                    .addComponent(txtDireccion)
                                    .addComponent(txtMunicipio)
                                    .addGroup(pnlPropLayout.createSequentialGroup()
                                        .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCalidad)
                                            .addComponent(lblDireccion)
                                            .addComponent(lblMunicipio)
                                            .addComponent(lblPropiedad))
                                        .addGap(0, 107, Short.MAX_VALUE))
                                    .addComponent(txtPropiedad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRegistrarProp, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))))
        );
        pnlPropLayout.setVerticalGroup(
            pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPropLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblCalidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlPropLayout.createSequentialGroup()
                        .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCedula)
                            .addComponent(lblDireccion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbTipoDocu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCorreo)
                            .addComponent(lblMunicipio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFecNac)
                            .addComponent(lblPropiedad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFecNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnRegistrarProp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTblContribuyentes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTblDatosContribuyentes, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        tabPaneRecaudo.addTab("Contribuyente", pnlProp);

        pnlVehiculo.setBackground(new java.awt.Color(204, 204, 204));

        txtPlaca.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });

        txtValor.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        txtCilindraje.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtCilindraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCilindrajeActionPerformed(evt);
            }
        });

        lblModelo.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblModelo.setText("Modelo");

        lblMarca.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblMarca.setText("Marca");

        lblValor.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblValor.setText("Valor");

        txtModelo.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });

        lblPlaca.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblPlaca.setText("Placa ");

        txtMarca.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });

        lblCilindraje.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblCilindraje.setText("Cilindraje");

        lblCombustible.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblCombustible.setText("Combustible");

        txtCanPas.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtCanPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCanPasActionPerformed(evt);
            }
        });

        cmbVehiculo.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        cmbVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Vehiculo", "Carro", "Moto" }));
        cmbVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVehiculoActionPerformed(evt);
            }
        });

        btnRegistrar.setBackground(new java.awt.Color(255, 255, 204));
        btnRegistrar.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lblCantPas.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblCantPas.setText("Cant pasajeros");

        lblTblDatosVehiculo.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblTblDatosVehiculo.setText("DATOS DE VEHICULO REGISTRADO");

        tblDatosVehiculo.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tblDatosVehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Placa", "Marca", "Modelo", "Cilindraje", "Cant Pas", "Valor", "Impuesto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollTblDatosVehiculo.setViewportView(tblDatosVehiculo);

        btnCambiarVehiculo.setBackground(new java.awt.Color(255, 255, 204));
        btnCambiarVehiculo.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnCambiarVehiculo.setForeground(new java.awt.Color(0, 0, 0));
        btnCambiarVehiculo.setText("CAMBIAR");
        btnCambiarVehiculo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCambiarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarVehiculoActionPerformed(evt);
            }
        });

        lblTipo.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblTipo.setText("Tipo");

        txtCombustible.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtCombustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCombustibleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlVehiculoLayout = new javax.swing.GroupLayout(pnlVehiculo);
        pnlVehiculo.setLayout(pnlVehiculoLayout);
        pnlVehiculoLayout.setHorizontalGroup(
            pnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVehiculoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator5)
                    .addComponent(jSeparator4)
                    .addGroup(pnlVehiculoLayout.createSequentialGroup()
                        .addGroup(pnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollTblDatosVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlVehiculoLayout.createSequentialGroup()
                                .addGroup(pnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlVehiculoLayout.createSequentialGroup()
                                            .addGap(39, 39, 39)
                                            .addComponent(lblPlaca))
                                        .addGroup(pnlVehiculoLayout.createSequentialGroup()
                                            .addGap(35, 35, 35)
                                            .addComponent(lblModelo)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVehiculoLayout.createSequentialGroup()
                                        .addGap(0, 0, 0)
                                        .addComponent(lblValor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(pnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVehiculoLayout.createSequentialGroup()
                                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(lblCilindraje)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlVehiculoLayout.createSequentialGroup()
                                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57)
                                        .addComponent(lblMarca)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMarca))
                                    .addGroup(pnlVehiculoLayout.createSequentialGroup()
                                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCombustible)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlVehiculoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlVehiculoLayout.createSequentialGroup()
                                .addComponent(lblTblDatosVehiculo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlVehiculoLayout.createSequentialGroup()
                                .addComponent(lblTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCantPas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCanPas)))))
                .addGap(18, 18, 18)
                .addGroup(pnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCambiarVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlVehiculoLayout.setVerticalGroup(
            pnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVehiculoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVehiculoLayout.createSequentialGroup()
                        .addGroup(pnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPlaca)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMarca)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblModelo)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCilindraje)
                            .addComponent(txtCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValor)
                            .addComponent(lblCombustible)
                            .addComponent(txtCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipo)
                            .addComponent(cmbVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCantPas)
                            .addComponent(txtCanPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTblDatosVehiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCambiarVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(scrollTblDatosVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPaneRecaudo.addTab("Vehiculo", pnlVehiculo);

        pnlRecaudo.setBackground(new java.awt.Color(204, 204, 255));

        tblDatosVehiRecaudo.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tblDatosVehiRecaudo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Placa", "Marca", "Modelo", "Cilindraje", "Cant Pas", "Valor", "Impuesto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollTblVehiRecaudo.setViewportView(tblDatosVehiRecaudo);

        btnRecaudo.setBackground(new java.awt.Color(255, 255, 204));
        btnRecaudo.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnRecaudo.setText("RECAUDO");
        btnRecaudo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtRecaudo.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtRecaudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecaudoActionPerformed(evt);
            }
        });

        lblRecaudoTotal.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblRecaudoTotal.setText("Recaudo Total");

        cmbNFormulario.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        cmbNFormulario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione N° De Formulario" }));

        tblDatosContRecaudo.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tblDatosContRecaudo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Documento", "Edad", "Calidad", "Correo", "Direccion", "Municipio", "% Propiedad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollTblDatosContRecaudo.setViewportView(tblDatosContRecaudo);

        NFormulario.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        NFormulario.setText("N° DE FORMULARIO");

        lblTblVehiRecaudo.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        lblTblVehiRecaudo.setText("VEHICULO");

        lblTblContRecaudo.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        lblTblContRecaudo.setText("CONTRIBUYENTES");

        btnEditar.setBackground(new java.awt.Color(255, 204, 255));
        btnEditar.setText("EDITAR");
        btnEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnBuscar.setBackground(new java.awt.Color(255, 204, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pnlRecaudoLayout = new javax.swing.GroupLayout(pnlRecaudo);
        pnlRecaudo.setLayout(pnlRecaudoLayout);
        pnlRecaudoLayout.setHorizontalGroup(
            pnlRecaudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecaudoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRecaudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRecaudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRecaudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollTblVehiRecaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollTblDatosContRecaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblTblContRecaudo))
                    .addComponent(lblTblVehiRecaudo)
                    .addGroup(pnlRecaudoLayout.createSequentialGroup()
                        .addComponent(NFormulario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbNFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRecaudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRecaudo, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(txtRecaudo)
                    .addGroup(pnlRecaudoLayout.createSequentialGroup()
                        .addComponent(lblRecaudoTotal)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        pnlRecaudoLayout.setVerticalGroup(
            pnlRecaudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRecaudoLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pnlRecaudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRecaudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(NFormulario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbNFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRecaudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(lblTblVehiRecaudo)
                .addGap(6, 6, 6)
                .addGroup(pnlRecaudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRecaudoLayout.createSequentialGroup()
                        .addComponent(scrollTblVehiRecaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTblContRecaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(scrollTblDatosContRecaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(pnlRecaudoLayout.createSequentialGroup()
                        .addComponent(btnRecaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRecaudoTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRecaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tabPaneRecaudo.addTab("Consulta Recaudo", pnlRecaudo);

        tbAvisos.setRollover(true);
        tbAvisos.setEnabled(false);
        tbAvisos.setMaximumSize(new java.awt.Dimension(540, 540));
        tbAvisos.setMinimumSize(new java.awt.Dimension(100, 100));
        tbAvisos.setPreferredSize(new java.awt.Dimension(100, 100));

        lbAvisos.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        tbAvisos.add(lbAvisos);

        btnAnadirFormulario.setBackground(new java.awt.Color(255, 102, 102));
        btnAnadirFormulario.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        btnAnadirFormulario.setForeground(new java.awt.Color(255, 255, 255));
        btnAnadirFormulario.setText("Añadir Formulario");
        btnAnadirFormulario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabPaneRecaudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnadirFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbAvisos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tabPaneRecaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbAvisos, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAnadirFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarPropActionPerformed

    private void txtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPropiedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPropiedadActionPerformed

    private void txtRecaudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecaudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecaudoActionPerformed

    private void txtFecNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFecNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFecNacActionPerformed

    private void txtCombustibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCombustibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCombustibleActionPerformed

    private void btnCambiarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambiarVehiculoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cmbVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbVehiculoActionPerformed

    private void txtCanPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCanPasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCanPasActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void txtCilindrajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCilindrajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCilindrajeActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    /**
     *
     * @return
     */
    public JLabel getNFormulario() {
        return NFormulario;
    }

    /**
     *
     * @param NFormulario
     */
    public void setNFormulario(JLabel NFormulario) {
        this.NFormulario = NFormulario;
    }

    /**
     *
     * @return
     */
    public JButton getBtnAnadirFormulario() {
        return btnAnadirFormulario;
    }

    /**
     *
     * @return
     */
    public JLabel getLbAvisos() {
        return lbAvisos;
    }

    /**
     *
     * @param lbAvisos
     */
    public void setLbAvisos(JLabel lbAvisos) {
        this.lbAvisos = lbAvisos;
    }
        
    /**
     *
     * @return
     */
    public JToolBar getTbAvisos() {
        return tbAvisos;
    }

    /**
     *
     * @param tbAvisos
     */
    public void setTbAvisos(JToolBar tbAvisos) {
        this.tbAvisos = tbAvisos;
    }

    /**
     *
     * @param btnAnadirFormulario
     */
    public void setBtnAnadirFormulario(JButton btnAnadirFormulario) {
        this.btnAnadirFormulario = btnAnadirFormulario;
    }

    /**
     *
     * @return
     */
    public JButton getBtnBorrarVehiculo() {
        return btnCambiarVehiculo;
    }

    /**
     *
     * @param btnBorrarVehiculo
     */
    public void setBtnBorrarVehiculo(JButton btnBorrarVehiculo) {
        this.btnCambiarVehiculo = btnBorrarVehiculo;
    }

    /**
     *
     * @return
     */
    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    /**
     *
     * @param btnBuscar
     */
    public void setBtnBuscar(JButton btnBuscar) {
        this.btnBuscar = btnBuscar;
    }
    
    /**
     *
     * @return
     */
    public JButton getBtnRecaudo() {
        return btnRecaudo;
    }

    /**
     *
     * @param btnRecaudo
     */
    public void setBtnRecaudo(JButton btnRecaudo) {
        this.btnRecaudo = btnRecaudo;
    }

    /**
     *
     * @return
     */
    public JButton getBtnRegistrar() {
        return btnRegistrar;
    }

    /**
     *
     * @param btnRegistrar
     */
    public void setBtnRegistrar(JButton btnRegistrar) {
        this.btnRegistrar = btnRegistrar;
    }

    /**
     *
     * @return
     */
    public JButton getBtnRegistrarProp() {
        return btnRegistrarProp;
    }

    /**
     *
     * @param btnRegistrarProp
     */
    public void setBtnRegistrarProp(JButton btnRegistrarProp) {
        this.btnRegistrarProp = btnRegistrarProp;
    }

    /**
     *
     * @return
     */
    public JComboBox<String> getCmbNFormulario() {
        return cmbNFormulario;
    }

    /**
     *
     * @param cmbNFormulario
     */
    public void setCmbNFormulario(JComboBox<String> cmbNFormulario) {
        this.cmbNFormulario = cmbNFormulario;
    }

    /**
     *
     * @return
     */
    public JComboBox<String> getCmbTipoDocu() {
        return cmbTipoDocu;
    }

    /**
     *
     * @param cmbTipoDocu
     */
    public void setCmbTipoDocu(JComboBox<String> cmbTipoDocu) {
        this.cmbTipoDocu = cmbTipoDocu;
    }

    /**
     *
     * @return
     */
    public JComboBox<String> getCmbVehiculo() {
        return cmbVehiculo;
    }

    /**
     *
     * @param cmbVehiculo
     */
    public void setCmbVehiculo(JComboBox<String> cmbVehiculo) {
        this.cmbVehiculo = cmbVehiculo;
    }

    /**
     *
     * @return
     */
    public JLabel getLblCalidad() {
        return lblCalidad;
    }

    /**
     *
     * @param lblCalidad
     */
    public void setLblCalidad(JLabel lblCalidad) {
        this.lblCalidad = lblCalidad;
    }

    /**
     *
     * @return
     */
    public JLabel getLblCantPas() {
        return lblCantPas;
    }

    /**
     *
     * @param lblCantPas
     */
    public void setLblCantPas(JLabel lblCantPas) {
        this.lblCantPas = lblCantPas;
    }

    /**
     *
     * @return
     */
    public JLabel getLblCedula() {
        return lblCedula;
    }

    /**
     *
     * @param lblCedula
     */
    public void setLblCedula(JLabel lblCedula) {
        this.lblCedula = lblCedula;
    }

    /**
     *
     * @return
     */
    public JLabel getLblCilindraje() {
        return lblCilindraje;
    }

    /**
     *
     * @param lblCilindraje
     */
    public void setLblCilindraje(JLabel lblCilindraje) {
        this.lblCilindraje = lblCilindraje;
    }

    /**
     *
     * @return
     */
    public JLabel getLblCombustible() {
        return lblCombustible;
    }

    /**
     *
     * @param lblCombustible
     */
    public void setLblCombustible(JLabel lblCombustible) {
        this.lblCombustible = lblCombustible;
    }

    /**
     *
     * @return
     */
    public JLabel getLblCorreo() {
        return lblCorreo;
    }

    /**
     *
     * @param lblCorreo
     */
    public void setLblCorreo(JLabel lblCorreo) {
        this.lblCorreo = lblCorreo;
    }

    /**
     *
     * @return
     */
    public JLabel getLblDireccion() {
        return lblDireccion;
    }

    /**
     *
     * @param lblDireccion
     */
    public void setLblDireccion(JLabel lblDireccion) {
        this.lblDireccion = lblDireccion;
    }

    /**
     *
     * @return
     */
    public JLabel getLblFecNac() {
        return lblFecNac;
    }

    /**
     *
     * @param lblFecNac
     */
    public void setLblFecNac(JLabel lblFecNac) {
        this.lblFecNac = lblFecNac;
    }

    /**
     *
     * @return
     */
    public JButton getBtnCambiarVehiculo() {
        return btnCambiarVehiculo;
    }

    /**
     *
     * @param btnCambiarVehiculo
     */
    public void setBtnCambiarVehiculo(JButton btnCambiarVehiculo) {
        this.btnCambiarVehiculo = btnCambiarVehiculo;
    }
    
    /**
     *
     * @return
     */
    public JLabel getLblMarca() {
        return lblMarca;
    }

    /**
     *
     * @param lblMarca
     */
    public void setLblMarca(JLabel lblMarca) {
        this.lblMarca = lblMarca;
    }

    /**
     *
     * @return
     */
    public JLabel getLblModelo() {
        return lblModelo;
    }

    /**
     *
     * @param lblModelo
     */
    public void setLblModelo(JLabel lblModelo) {
        this.lblModelo = lblModelo;
    }

    /**
     *
     * @return
     */
    public JLabel getLblMunicipio() {
        return lblMunicipio;
    }

    /**
     *
     * @param lblMunicipio
     */
    public void setLblMunicipio(JLabel lblMunicipio) {
        this.lblMunicipio = lblMunicipio;
    }

    /**
     *
     * @return
     */
    public JLabel getLblNombre() {
        return lblNombre;
    }

    /**
     *
     * @param lblNombre
     */
    public void setLblNombre(JLabel lblNombre) {
        this.lblNombre = lblNombre;
    }

    /**
     *
     * @return
     */
    public JLabel getLblPlaca() {
        return lblPlaca;
    }

    /**
     *
     * @param lblPlaca
     */
    public void setLblPlaca(JLabel lblPlaca) {
        this.lblPlaca = lblPlaca;
    }

    /**
     *
     * @return
     */
    public JLabel getLblPropiedad() {
        return lblPropiedad;
    }

    /**
     *
     * @param lblPropiedad
     */
    public void setLblPropiedad(JLabel lblPropiedad) {
        this.lblPropiedad = lblPropiedad;
    }

    /**
     *
     * @return
     */
    public JLabel getLblRecaudoTotal() {
        return lblRecaudoTotal;
    }

    /**
     *
     * @param lblRecaudoTotal
     */
    public void setLblRecaudoTotal(JLabel lblRecaudoTotal) {
        this.lblRecaudoTotal = lblRecaudoTotal;
    }

    /**
     *
     * @return
     */
    public JLabel getLblTblContRecaudo() {
        return lblTblContRecaudo;
    }

    /**
     *
     * @param lblTblContRecaudo
     */
    public void setLblTblContRecaudo(JLabel lblTblContRecaudo) {
        this.lblTblContRecaudo = lblTblContRecaudo;
    }

    /**
     *
     * @return
     */
    public JLabel getLblTblContribuyentes() {
        return lblTblContribuyentes;
    }

    /**
     *
     * @param lblTblContribuyentes
     */
    public void setLblTblContribuyentes(JLabel lblTblContribuyentes) {
        this.lblTblContribuyentes = lblTblContribuyentes;
    }

    /**
     *
     * @return
     */
    public JLabel getLblTblDatosVehiculo() {
        return lblTblDatosVehiculo;
    }

    /**
     *
     * @param lblTblDatosVehiculo
     */
    public void setLblTblDatosVehiculo(JLabel lblTblDatosVehiculo) {
        this.lblTblDatosVehiculo = lblTblDatosVehiculo;
    }

    /**
     *
     * @return
     */
    public JLabel getLblTblVehiRecaudo() {
        return lblTblVehiRecaudo;
    }

    /**
     *
     * @param lblTblVehiRecaudo
     */
    public void setLblTblVehiRecaudo(JLabel lblTblVehiRecaudo) {
        this.lblTblVehiRecaudo = lblTblVehiRecaudo;
    }

    /**
     *
     * @return
     */
    public JLabel getLblTipo() {
        return lblTipo;
    }

    /**
     *
     * @param lblTipo
     */
    public void setLblTipo(JLabel lblTipo) {
        this.lblTipo = lblTipo;
    }

    /**
     *
     * @return
     */
    public JLabel getLblValor() {
        return lblValor;
    }

    /**
     *
     * @param lblValor
     */
    public void setLblValor(JLabel lblValor) {
        this.lblValor = lblValor;
    }

    /**
     *
     * @return
     */
    public JPanel getPnlRecaudo() {
        return pnlRecaudo;
    }

    /**
     *
     * @param pnlRecaudo
     */
    public void setPnlRecaudo(JPanel pnlRecaudo) {
        this.pnlRecaudo = pnlRecaudo;
    }

    /**
     *
     * @return
     */
    public JTabbedPane getTabPaneRecaudo() {
        return tabPaneRecaudo;
    }

    /**
     *
     * @param tabPaneRecaudo
     */
    public void setTabPaneRecaudo(JTabbedPane tabPaneRecaudo) {
        this.tabPaneRecaudo = tabPaneRecaudo;
    }

    /**
     *
     * @return
     */
    public JPanel getPnlProp() {
        return pnlProp;
    }

    /**
     *
     * @param pnlProp
     */
    public void setPnlProp(JPanel pnlProp) {
        this.pnlProp = pnlProp;
    }

    /**
     *
     * @return
     */
    public JPanel getPnlVehiculo() {
        return pnlVehiculo;
    }

    /**
     *
     * @param pnlVehiculo
     */
    public void setPnlVehiculo(JPanel pnlVehiculo) {
        this.pnlVehiculo = pnlVehiculo;
    }

    /**
     *
     * @return
     */
    public JScrollPane getScrollTblDatosContRecaudo() {
        return scrollTblDatosContRecaudo;
    }

    /**
     *
     * @param scrollTblDatosContRecaudo
     */
    public void setScrollTblDatosContRecaudo(JScrollPane scrollTblDatosContRecaudo) {
        this.scrollTblDatosContRecaudo = scrollTblDatosContRecaudo;
    }

    /**
     *
     * @return
     */
    public JScrollPane getScrollTblDatosContribuyentes() {
        return scrollTblDatosContribuyentes;
    }

    /**
     *
     * @param scrollTblDatosContribuyentes
     */
    public void setScrollTblDatosContribuyentes(JScrollPane scrollTblDatosContribuyentes) {
        this.scrollTblDatosContribuyentes = scrollTblDatosContribuyentes;
    }

    /**
     *
     * @return
     */
    public JScrollPane getScrollTblDatosVehiculo() {
        return scrollTblDatosVehiculo;
    }

    /**
     *
     * @param scrollTblDatosVehiculo
     */
    public void setScrollTblDatosVehiculo(JScrollPane scrollTblDatosVehiculo) {
        this.scrollTblDatosVehiculo = scrollTblDatosVehiculo;
    }

    /**
     *
     * @return
     */
    public JScrollPane getScrollTblVehiRecaudo() {
        return scrollTblVehiRecaudo;
    }

    /**
     *
     * @param scrollTblVehiRecaudo
     */
    public void setScrollTblVehiRecaudo(JScrollPane scrollTblVehiRecaudo) {
        this.scrollTblVehiRecaudo = scrollTblVehiRecaudo;
    }

    /**
     *
     * @return
     */
    public JTabbedPane getTabPaneVehiculo() {
        return tabPaneRecaudo;
    }

    /**
     *
     * @param tabPaneVehiculo
     */
    public void setTabPaneVehiculo(JTabbedPane tabPaneVehiculo) {
        this.tabPaneRecaudo = tabPaneVehiculo;
    }

    /**
     *
     * @return
     */
    public JTable getTblDatosContRecaudo() {
        return tblDatosContRecaudo;
    }

    /**
     *
     * @param tblDatosContRecaudo
     */
    public void setTblDatosContRecaudo(JTable tblDatosContRecaudo) {
        this.tblDatosContRecaudo = tblDatosContRecaudo;
    }

    /**
     *
     * @return
     */
    public JTable getTblDatosContibuyentes() {
        return tblDatosContibuyentes;
    }

    /**
     *
     * @param tblDatosContibuyentes
     */
    public void setTblDatosContibuyentes(JTable tblDatosContibuyentes) {
        this.tblDatosContibuyentes = tblDatosContibuyentes;
    }

    /**
     *
     * @return
     */
    public JTable getTblDatosVehiRecaudo() {
        return tblDatosVehiRecaudo;
    }

    /**
     *
     * @param tblDatosVehiRecaudo
     */
    public void setTblDatosVehiRecaudo(JTable tblDatosVehiRecaudo) {
        this.tblDatosVehiRecaudo = tblDatosVehiRecaudo;
    }

    /**
     *
     * @return
     */
    public JTable getTblDatosVehiculo() {
        return tblDatosVehiculo;
    }

    /**
     *
     * @param tblDatosVehiculo
     */
    public void setTblDatosVehiculo(JTable tblDatosVehiculo) {
        this.tblDatosVehiculo = tblDatosVehiculo;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtCalidad() {
        return txtCalidad;
    }

    /**
     *
     * @param txtCalidad
     */
    public void setTxtCalidad(JTextField txtCalidad) {
        this.txtCalidad = txtCalidad;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtCanPas() {
        return txtCanPas;
    }

    /**
     *
     * @param txtCanPas
     */
    public void setTxtCanPas(JTextField txtCanPas) {
        this.txtCanPas = txtCanPas;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtCedula() {
        return txtCedula;
    }

    /**
     *
     * @param txtCedula
     */
    public void setTxtCedula(JTextField txtCedula) {
        this.txtCedula = txtCedula;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtCilindraje() {
        return txtCilindraje;
    }

    /**
     *
     * @param txtCilindraje
     */
    public void setTxtCilindraje(JTextField txtCilindraje) {
        this.txtCilindraje = txtCilindraje;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtCombustible() {
        return txtCombustible;
    }

    /**
     *
     * @param txtCombustible
     */
    public void setTxtCombustible(JTextField txtCombustible) {
        this.txtCombustible = txtCombustible;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtCorreo() {
        return txtCorreo;
    }

    /**
     *
     * @param txtCorreo
     */
    public void setTxtCorreo(JTextField txtCorreo) {
        this.txtCorreo = txtCorreo;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtDireccion() {
        return txtDireccion;
    }

    /**
     *
     * @param txtDireccion
     */
    public void setTxtDireccion(JTextField txtDireccion) {
        this.txtDireccion = txtDireccion;
    }

    /**
     *
     * @return
     */
    public JButton getBtnEditar() {
        return btnEditar;
    }

    /**
     *
     * @param btnEditar
     */
    public void setBtnEditar(JButton btnEditar) {
        this.btnEditar = btnEditar;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtFecNac() {
        return txtFecNac;
    }

    /**
     *
     * @param txtFecNac
     */
    public void setTxtFecNac(JTextField txtFecNac) {
        this.txtFecNac = txtFecNac;
    }
    
    /**
     *
     * @return
     */
    public JTextField getTxtMarca() {
        return txtMarca;
    }

    /**
     *
     * @param txtMarca
     */
    public void setTxtMarca(JTextField txtMarca) {
        this.txtMarca = txtMarca;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtModelo() {
        return txtModelo;
    }

    /**
     *
     * @param txtModelo
     */
    public void setTxtModelo(JTextField txtModelo) {
        this.txtModelo = txtModelo;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtMunicipio() {
        return txtMunicipio;
    }

    /**
     *
     * @param txtMunicipio
     */
    public void setTxtMunicipio(JTextField txtMunicipio) {
        this.txtMunicipio = txtMunicipio;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtNom() {
        return txtNom;
    }

    /**
     *
     * @param txtNom
     */
    public void setTxtNom(JTextField txtNom) {
        this.txtNom = txtNom;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtPlaca() {
        return txtPlaca;
    }

    /**
     *
     * @param txtPlaca
     */
    public void setTxtPlaca(JTextField txtPlaca) {
        this.txtPlaca = txtPlaca;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtPropiedad() {
        return txtPropiedad;
    }

    /**
     *
     * @param txtPropiedad
     */
    public void setTxtPropiedad(JTextField txtPropiedad) {
        this.txtPropiedad = txtPropiedad;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtRecaudo() {
        return txtRecaudo;
    }

    /**
     *
     * @param txtRecaudo
     */
    public void setTxtRecaudo(JTextField txtRecaudo) {
        this.txtRecaudo = txtRecaudo;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtValor() {
        return txtValor;
    }

    /**
     *
     * @param txtValor
     */
    public void setTxtValor(JTextField txtValor) {
        this.txtValor = txtValor;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NFormulario;
    private javax.swing.JButton btnAnadirFormulario;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCambiarVehiculo;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRecaudo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrarProp;
    private javax.swing.JComboBox<String> cmbNFormulario;
    private javax.swing.JComboBox<String> cmbTipoDocu;
    private javax.swing.JComboBox<String> cmbVehiculo;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbAvisos;
    private javax.swing.JLabel lblCalidad;
    private javax.swing.JLabel lblCantPas;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCilindraje;
    private javax.swing.JLabel lblCombustible;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFecNac;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblMunicipio;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblPropiedad;
    private javax.swing.JLabel lblRecaudoTotal;
    private javax.swing.JLabel lblTblContRecaudo;
    private javax.swing.JLabel lblTblContribuyentes;
    private javax.swing.JLabel lblTblDatosVehiculo;
    private javax.swing.JLabel lblTblVehiRecaudo;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JPanel pnlProp;
    private javax.swing.JPanel pnlRecaudo;
    private javax.swing.JPanel pnlVehiculo;
    private javax.swing.JScrollPane scrollTblDatosContRecaudo;
    private javax.swing.JScrollPane scrollTblDatosContribuyentes;
    private javax.swing.JScrollPane scrollTblDatosVehiculo;
    private javax.swing.JScrollPane scrollTblVehiRecaudo;
    private javax.swing.JTabbedPane tabPaneRecaudo;
    private javax.swing.JToolBar tbAvisos;
    private javax.swing.JTable tblDatosContRecaudo;
    private javax.swing.JTable tblDatosContibuyentes;
    private javax.swing.JTable tblDatosVehiRecaudo;
    private javax.swing.JTable tblDatosVehiculo;
    private javax.swing.JTextField txtCalidad;
    private javax.swing.JTextField txtCanPas;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCilindraje;
    private javax.swing.JTextField txtCombustible;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFecNac;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtMunicipio;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPropiedad;
    private javax.swing.JTextField txtRecaudo;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
