/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author Dyl
 */
public class IfrmConsulRecaudo extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmConsulRecaudo
     */
    public IfrmConsulRecaudo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRecaudo = new javax.swing.JTextField();
        lblRecaudoTotal = new javax.swing.JLabel();
        cmbNFormulario = new javax.swing.JComboBox<>();
        scrollTblDatosContRecaudo = new javax.swing.JScrollPane();
        tblDatosContRecaudo = new javax.swing.JTable();
        NFormulario = new javax.swing.JLabel();
        lblTblVehiRecaudo = new javax.swing.JLabel();
        lblTblContRecaudo = new javax.swing.JLabel();
        scrollTblVehiRecaudo = new javax.swing.JScrollPane();
        tblDatosVehiRecaudo = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnRecaudo = new javax.swing.JButton();
        lblValSemaforizacion = new javax.swing.JLabel();
        txtValSemaforizacion = new javax.swing.JTextField();
        lblDescCombustible = new javax.swing.JLabel();
        txtDescCombus = new javax.swing.JTextField();
        lblDescProntoP = new javax.swing.JLabel();
        txtDescProntoP = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblPagoVoluntario = new javax.swing.JLabel();
        txtPagoVoluntario = new javax.swing.JTextField();
        lblTotalPagoV = new javax.swing.JLabel();
        txtTotalPagoV = new javax.swing.JTextField();
        separador1 = new javax.swing.JSeparator();
        separador2 = new javax.swing.JSeparator();
        btnPDF = new javax.swing.JButton();
        lblTotalDescPP = new javax.swing.JLabel();
        txtTotalDescPP = new javax.swing.JTextField();
        lblTotalPVolDescPP = new javax.swing.JLabel();
        txtTotalPVolDescPP = new javax.swing.JTextField();
        separador3 = new javax.swing.JSeparator();
        btnReintentar = new javax.swing.JButton();
        lblFechaOp = new javax.swing.JLabel();
        txtFechaOp = new javax.swing.JTextField();
        lblFechaLim = new javax.swing.JLabel();
        txtFechaLim = new javax.swing.JTextField();
        separador4 = new javax.swing.JSeparator();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar Recaudo Formularios");

        txtRecaudo.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtRecaudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecaudoActionPerformed(evt);
            }
        });

        lblRecaudoTotal.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblRecaudoTotal.setText("Recaudo Total");

        cmbNFormulario.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        cmbNFormulario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione N° De Formulario" }));

        tblDatosContRecaudo.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tblDatosContRecaudo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Documento", "Edad", "Calidad", "Correo", "Direccion", "Municipio", "% Propiedad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollTblDatosContRecaudo.setViewportView(tblDatosContRecaudo);

        NFormulario.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        NFormulario.setText("N° DE FORMULARIO");

        lblTblVehiRecaudo.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        lblTblVehiRecaudo.setText("VEHICULO");

        lblTblContRecaudo.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        lblTblContRecaudo.setText("CONTRIBUYENTES");

        tblDatosVehiRecaudo.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tblDatosVehiRecaudo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Placa", "Marca", "Modelo", "Cilindraje", "Cant Pas", "Valor", "Impuesto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollTblVehiRecaudo.setViewportView(tblDatosVehiRecaudo);

        btnEditar.setBackground(new java.awt.Color(255, 204, 255));
        btnEditar.setText("EDITAR");
        btnEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnBuscar.setBackground(new java.awt.Color(255, 204, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnRecaudo.setBackground(new java.awt.Color(255, 255, 204));
        btnRecaudo.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnRecaudo.setText("RECAUDO");
        btnRecaudo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblValSemaforizacion.setText("Valor Semaforizacion");

        lblDescCombustible.setText("Descuento Combustible");

        lblDescProntoP.setText("Descuento Pronto Pago");

        lblTotal.setText("Total a Pagar");

        lblPagoVoluntario.setText("Pago Voluntario");

        lblTotalPagoV.setText("Total con P. Voluntario");

        separador1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        separador2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnPDF.setBackground(new java.awt.Color(255, 102, 102));
        btnPDF.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnPDF.setForeground(new java.awt.Color(255, 255, 255));
        btnPDF.setText("EXPORTAR PDF");
        btnPDF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        lblTotalDescPP.setText("Total con Desc. Pronto Pago");

        lblTotalPVolDescPP.setText("Total con P Vol y D pronto P");

        separador3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnReintentar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Reintentar.png"))); // NOI18N

        lblFechaOp.setText("Fecha Oportuna");

        lblFechaLim.setText("Fecha Limite");

        separador4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollTblVehiRecaudo)
                            .addComponent(scrollTblDatosContRecaudo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NFormulario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbNFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReintentar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(2, 2, 2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTblContRecaudo)
                                    .addComponent(lblTblVehiRecaudo))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRecaudoTotal)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtRecaudo)
                            .addComponent(btnRecaudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotal)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtValSemaforizacion, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblValSemaforizacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPagoVoluntario, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPagoVoluntario)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblDescCombustible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDescCombus, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTotalPagoV, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTotalPagoV, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(txtDescProntoP, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescProntoP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separador3, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTotalPVolDescPP, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTotalPVolDescPP, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(txtTotalDescPP, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalDescPP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(separador4, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFechaLim)
                            .addComponent(txtFechaOp)
                            .addComponent(lblFechaOp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFechaLim))))
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NFormulario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbNFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnReintentar)))
                .addGap(7, 7, 7)
                .addComponent(lblTblVehiRecaudo)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollTblVehiRecaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTblContRecaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(scrollTblDatosContRecaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRecaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(lblRecaudoTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRecaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separador3)
                    .addComponent(separador2)
                    .addComponent(separador1)
                    .addComponent(separador4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTotalDescPP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalDescPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalPVolDescPP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalPVolDescPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblValSemaforizacion)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtValSemaforizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblTotal)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblDescCombustible)
                                        .addComponent(lblDescProntoP))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDescCombus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDescProntoP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblPagoVoluntario)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtPagoVoluntario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblTotalPagoV)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtTotalPagoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFechaOp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFechaLim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaLim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRecaudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecaudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecaudoActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPDFActionPerformed

    /**
     *
     * @return
     */
    public JLabel getLblFechaLim() {
        return lblFechaLim;
    }

    /**
     *
     * @param lblFechaLim
     */
    public void setLblFechaLim(JLabel lblFechaLim) {
        this.lblFechaLim = lblFechaLim;
    }

    /**
     *
     * @return
     */
    public JLabel getLblFechaOp() {
        return lblFechaOp;
    }

    /**
     *
     * @param lblFechaOp
     */
    public void setLblFechaOp(JLabel lblFechaOp) {
        this.lblFechaOp = lblFechaOp;
    }

    /**
     *
     * @return
     */
    public JSeparator getSeparador4() {
        return separador4;
    }

    /**
     *
     * @param separador4
     */
    public void setSeparador4(JSeparator separador4) {
        this.separador4 = separador4;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtFechaLim() {
        return txtFechaLim;
    }

    /**
     *
     * @param txtFechaLim
     */
    public void setTxtFechaLim(JTextField txtFechaLim) {
        this.txtFechaLim = txtFechaLim;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtFechaOp() {
        return txtFechaOp;
    }

    /**
     *
     * @param txtFechaOp
     */
    public void setTxtFechaOp(JTextField txtFechaOp) {
        this.txtFechaOp = txtFechaOp;
    }

    /**
     *
     * @return
     */
    public JButton getBtnReintentar() {
        return btnReintentar;
    }

    /**
     *
     * @param btnReintentar
     */
    public void setBtnReintentar(JButton btnReintentar) {
        this.btnReintentar = btnReintentar;
    }

    /**
     *
     * @return
     */
    public JLabel getLblTotalDescPP() {
        return lblTotalDescPP;
    }

    /**
     *
     * @param lblTotalDescPP
     */
    public void setLblTotalDescPP(JLabel lblTotalDescPP) {
        this.lblTotalDescPP = lblTotalDescPP;
    }

    /**
     *
     * @return
     */
    public JLabel getLblTotalPVolDescPP() {
        return lblTotalPVolDescPP;
    }

    /**
     *
     * @param lblTotalPVolDescPP
     */
    public void setLblTotalPVolDescPP(JLabel lblTotalPVolDescPP) {
        this.lblTotalPVolDescPP = lblTotalPVolDescPP;
    }

    /**
     *
     * @return
     */
    public JSeparator getSeparador3() {
        return separador3;
    }

    /**
     *
     * @param separador3
     */
    public void setSeparador3(JSeparator separador3) {
        this.separador3 = separador3;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtTotalDescPP() {
        return txtTotalDescPP;
    }

    /**
     *
     * @param txtTotalDescPP
     */
    public void setTxtTotalDescPP(JTextField txtTotalDescPP) {
        this.txtTotalDescPP = txtTotalDescPP;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtTotalPVolDescPP() {
        return txtTotalPVolDescPP;
    }

    /**
     *
     * @param txtTotalPVolDescPP
     */
    public void setTxtTotalPVolDescPP(JTextField txtTotalPVolDescPP) {
        this.txtTotalPVolDescPP = txtTotalPVolDescPP;
    }


    /**
     *
     * @return
     */
    public JButton getBtnPDF() {
        return btnPDF;
    }

    /**
     *
     * @param btnPDF
     */
    public void setBtnPDF(JButton btnPDF) {
        this.btnPDF = btnPDF;
    }

    /**
     *
     * @return
     */
    public JLabel getNFormulario() {
        return NFormulario;
    }

    /**
     *
     * @param NFormulario
     */
    public void setNFormulario(JLabel NFormulario) {
        this.NFormulario = NFormulario;
    }

    /**
     *
     * @return
     */
    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    /**
     *
     * @param btnBuscar
     */
    public void setBtnBuscar(JButton btnBuscar) {
        this.btnBuscar = btnBuscar;
    }

    /**
     *
     * @return
     */
    public JButton getBtnEditar() {
        return btnEditar;
    }

    /**
     *
     * @param btnEditar
     */
    public void setBtnEditar(JButton btnEditar) {
        this.btnEditar = btnEditar;
    }


    /**
     *
     * @return
     */
    public JButton getBtnRecaudo() {
        return btnRecaudo;
    }

    /**
     *
     * @param btnRecaudo
     */
    public void setBtnRecaudo(JButton btnRecaudo) {
        this.btnRecaudo = btnRecaudo;
    }

    /**
     *
     * @return
     */
    public JComboBox<String> getCmbNFormulario() {
        return cmbNFormulario;
    }

    /**
     *
     * @param cmbNFormulario
     */
    public void setCmbNFormulario(JComboBox<String> cmbNFormulario) {
        this.cmbNFormulario = cmbNFormulario;
    }

    /**
     *
     * @return
     */
    public JLabel getLblDescCombustible() {
        return lblDescCombustible;
    }

    /**
     *
     * @param lblDescCombustible
     */
    public void setLblDescCombustible(JLabel lblDescCombustible) {
        this.lblDescCombustible = lblDescCombustible;
    }

    /**
     *
     * @return
     */
    public JLabel getLblDescProntoP() {
        return lblDescProntoP;
    }

    /**
     *
     * @param lblDescProntoP
     */
    public void setLblDescProntoP(JLabel lblDescProntoP) {
        this.lblDescProntoP = lblDescProntoP;
    }

    /**
     *
     * @return
     */
    public JLabel getLblPagoVoluntario() {
        return lblPagoVoluntario;
    }

    /**
     *
     * @param lblPagoVoluntario
     */
    public void setLblPagoVoluntario(JLabel lblPagoVoluntario) {
        this.lblPagoVoluntario = lblPagoVoluntario;
    }

    /**
     *
     * @return
     */
    public JLabel getLblRecaudoTotal() {
        return lblRecaudoTotal;
    }

    /**
     *
     * @param lblRecaudoTotal
     */
    public void setLblRecaudoTotal(JLabel lblRecaudoTotal) {
        this.lblRecaudoTotal = lblRecaudoTotal;
    }

    /**
     *
     * @return
     */
    public JLabel getLblTblContRecaudo() {
        return lblTblContRecaudo;
    }

    /**
     *
     * @param lblTblContRecaudo
     */
    public void setLblTblContRecaudo(JLabel lblTblContRecaudo) {
        this.lblTblContRecaudo = lblTblContRecaudo;
    }

    /**
     *
     * @return
     */
    public JLabel getLblTblVehiRecaudo() {
        return lblTblVehiRecaudo;
    }

    /**
     *
     * @param lblTblVehiRecaudo
     */
    public void setLblTblVehiRecaudo(JLabel lblTblVehiRecaudo) {
        this.lblTblVehiRecaudo = lblTblVehiRecaudo;
    }

    /**
     *
     * @return
     */
    public JLabel getLblTotal() {
        return lblTotal;
    }

    /**
     *
     * @param lblTotal
     */
    public void setLblTotal(JLabel lblTotal) {
        this.lblTotal = lblTotal;
    }

    /**
     *
     * @return
     */
    public JLabel getLblTotalPagoV() {
        return lblTotalPagoV;
    }

    /**
     *
     * @param lblTotalPagoV
     */
    public void setLblTotalPagoV(JLabel lblTotalPagoV) {
        this.lblTotalPagoV = lblTotalPagoV;
    }

    /**
     *
     * @return
     */
    public JLabel getLblValSemaforizacion() {
        return lblValSemaforizacion;
    }

    /**
     *
     * @param lblValSemaforizacion
     */
    public void setLblValSemaforizacion(JLabel lblValSemaforizacion) {
        this.lblValSemaforizacion = lblValSemaforizacion;
    }

    /**
     *
     * @return
     */
    public JScrollPane getScrollTblDatosContRecaudo() {
        return scrollTblDatosContRecaudo;
    }

    /**
     *
     * @param scrollTblDatosContRecaudo
     */
    public void setScrollTblDatosContRecaudo(JScrollPane scrollTblDatosContRecaudo) {
        this.scrollTblDatosContRecaudo = scrollTblDatosContRecaudo;
    }

    /**
     *
     * @return
     */
    public JScrollPane getScrollTblVehiRecaudo() {
        return scrollTblVehiRecaudo;
    }

    /**
     *
     * @param scrollTblVehiRecaudo
     */
    public void setScrollTblVehiRecaudo(JScrollPane scrollTblVehiRecaudo) {
        this.scrollTblVehiRecaudo = scrollTblVehiRecaudo;
    }

    /**
     *
     * @return
     */
    public JSeparator getSeparador1() {
        return separador1;
    }

    /**
     *
     * @param separador1
     */
    public void setSeparador1(JSeparator separador1) {
        this.separador1 = separador1;
    }

    /**
     *
     * @return
     */
    public JSeparator getSeparador2() {
        return separador2;
    }

    /**
     *
     * @param separador2
     */
    public void setSeparador2(JSeparator separador2) {
        this.separador2 = separador2;
    }

    /**
     *
     * @return
     */
    public JTable getTblDatosContRecaudo() {
        return tblDatosContRecaudo;
    }

    /**
     *
     * @param tblDatosContRecaudo
     */
    public void setTblDatosContRecaudo(JTable tblDatosContRecaudo) {
        this.tblDatosContRecaudo = tblDatosContRecaudo;
    }

    /**
     *
     * @return
     */
    public JTable getTblDatosVehiRecaudo() {
        return tblDatosVehiRecaudo;
    }

    /**
     *
     * @param tblDatosVehiRecaudo
     */
    public void setTblDatosVehiRecaudo(JTable tblDatosVehiRecaudo) {
        this.tblDatosVehiRecaudo = tblDatosVehiRecaudo;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtDescCombus() {
        return txtDescCombus;
    }

    /**
     *
     * @param txtDescCombus
     */
    public void setTxtDescCombus(JTextField txtDescCombus) {
        this.txtDescCombus = txtDescCombus;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtDescProntoP() {
        return txtDescProntoP;
    }

    /**
     *
     * @param txtDescProntoP
     */
    public void setTxtDescProntoP(JTextField txtDescProntoP) {
        this.txtDescProntoP = txtDescProntoP;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtPagoVoluntario() {
        return txtPagoVoluntario;
    }

    /**
     *
     * @param txtPagoVoluntario
     */
    public void setTxtPagoVoluntario(JTextField txtPagoVoluntario) {
        this.txtPagoVoluntario = txtPagoVoluntario;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtRecaudo() {
        return txtRecaudo;
    }

    /**
     *
     * @param txtRecaudo
     */
    public void setTxtRecaudo(JTextField txtRecaudo) {
        this.txtRecaudo = txtRecaudo;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtTotal() {
        return txtTotal;
    }

    /**
     *
     * @param txtTotal
     */
    public void setTxtTotal(JTextField txtTotal) {
        this.txtTotal = txtTotal;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtTotalPagoV() {
        return txtTotalPagoV;
    }

    /**
     *
     * @param txtTotalPagoV
     */
    public void setTxtTotalPagoV(JTextField txtTotalPagoV) {
        this.txtTotalPagoV = txtTotalPagoV;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtValSemaforizacion() {
        return txtValSemaforizacion;
    }

    /**
     *
     * @param txtValSemaforizacion
     */
    public void setTxtValSemaforizacion(JTextField txtValSemaforizacion) {
        this.txtValSemaforizacion = txtValSemaforizacion;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NFormulario;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnRecaudo;
    private javax.swing.JButton btnReintentar;
    private javax.swing.JComboBox<String> cmbNFormulario;
    private javax.swing.JLabel lblDescCombustible;
    private javax.swing.JLabel lblDescProntoP;
    private javax.swing.JLabel lblFechaLim;
    private javax.swing.JLabel lblFechaOp;
    private javax.swing.JLabel lblPagoVoluntario;
    private javax.swing.JLabel lblRecaudoTotal;
    private javax.swing.JLabel lblTblContRecaudo;
    private javax.swing.JLabel lblTblVehiRecaudo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalDescPP;
    private javax.swing.JLabel lblTotalPVolDescPP;
    private javax.swing.JLabel lblTotalPagoV;
    private javax.swing.JLabel lblValSemaforizacion;
    private javax.swing.JScrollPane scrollTblDatosContRecaudo;
    private javax.swing.JScrollPane scrollTblVehiRecaudo;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JSeparator separador3;
    private javax.swing.JSeparator separador4;
    private javax.swing.JTable tblDatosContRecaudo;
    private javax.swing.JTable tblDatosVehiRecaudo;
    private javax.swing.JTextField txtDescCombus;
    private javax.swing.JTextField txtDescProntoP;
    private javax.swing.JTextField txtFechaLim;
    private javax.swing.JTextField txtFechaOp;
    private javax.swing.JTextField txtPagoVoluntario;
    private javax.swing.JTextField txtRecaudo;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalDescPP;
    private javax.swing.JTextField txtTotalPVolDescPP;
    private javax.swing.JTextField txtTotalPagoV;
    private javax.swing.JTextField txtValSemaforizacion;
    // End of variables declaration//GEN-END:variables
}
