/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Dyl
 */
public class IfrmConsulPropietarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmConsulPropietarios
     */
    public IfrmConsulPropietarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTblContribuyentes = new javax.swing.JLabel();
        scrollTblDatosContribuyentes = new javax.swing.JScrollPane();
        tblDatosContibuyentes = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar Propietarios");

        lblTblContribuyentes.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblTblContribuyentes.setText("CONTRIBUYENTES");

        tblDatosContibuyentes.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tblDatosContibuyentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Documento", "Correo", "Edad", "Calidad", "Direccion", "Municipio", "% Propiedad", "Nº Formulario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDatosContibuyentes.setEnabled(false);
        scrollTblDatosContribuyentes.setViewportView(tblDatosContibuyentes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTblDatosContribuyentes, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTblContribuyentes)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTblContribuyentes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTblDatosContribuyentes, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @return
     */
    public JLabel getLblTblContribuyentes() {
        return lblTblContribuyentes;
    }

    /**
     *
     * @param lblTblContribuyentes
     */
    public void setLblTblContribuyentes(JLabel lblTblContribuyentes) {
        this.lblTblContribuyentes = lblTblContribuyentes;
    }

    /**
     *
     * @return
     */
    public JScrollPane getScrollTblDatosContribuyentes() {
        return scrollTblDatosContribuyentes;
    }

    /**
     *
     * @param scrollTblDatosContribuyentes
     */
    public void setScrollTblDatosContribuyentes(JScrollPane scrollTblDatosContribuyentes) {
        this.scrollTblDatosContribuyentes = scrollTblDatosContribuyentes;
    }

    /**
     *
     * @return
     */
    public JTable getTblDatosContibuyentes() {
        return tblDatosContibuyentes;
    }

    /**
     *
     * @param tblDatosContibuyentes
     */
    public void setTblDatosContibuyentes(JTable tblDatosContibuyentes) {
        this.tblDatosContibuyentes = tblDatosContibuyentes;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTblContribuyentes;
    private javax.swing.JScrollPane scrollTblDatosContribuyentes;
    private javax.swing.JTable tblDatosContibuyentes;
    // End of variables declaration//GEN-END:variables
}
