/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Dyl
 */
public class IfrmAgFormulario extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmAgFormulario
     */
    public IfrmAgFormulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollTblDatosContRecaudo = new javax.swing.JScrollPane();
        tblDatosContRecaudo = new javax.swing.JTable();
        lblTblVehiRecaudo = new javax.swing.JLabel();
        lblTblContRecaudo = new javax.swing.JLabel();
        scrollTblVehiRecaudo = new javax.swing.JScrollPane();
        tblDatosVehiRecaudo = new javax.swing.JTable();
        lblFechaPagoOp = new javax.swing.JLabel();
        txtFechaPagoOp = new javax.swing.JTextField();
        lblFechaPagoTar = new javax.swing.JLabel();
        txtFechaPagoTar = new javax.swing.JTextField();
        btnAnadirFormulario = new javax.swing.JButton();
        separador = new javax.swing.JSeparator();
        lblDescuentoAdicional = new javax.swing.JLabel();
        cmbDescuentoAdd = new javax.swing.JComboBox<>();
        lblValDescuentoAdicional = new javax.swing.JLabel();
        txtDescuentoAdicional = new javax.swing.JTextField();
        lblNFactura = new javax.swing.JLabel();
        txtNFactura = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Agregar Formulario");

        tblDatosContRecaudo.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tblDatosContRecaudo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Documento", "Edad", "Calidad", "Correo", "Direccion", "Municipio", "% Propiedad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollTblDatosContRecaudo.setViewportView(tblDatosContRecaudo);

        lblTblVehiRecaudo.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        lblTblVehiRecaudo.setText("VEHICULO");

        lblTblContRecaudo.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        lblTblContRecaudo.setText("CONTRIBUYENTES");

        tblDatosVehiRecaudo.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tblDatosVehiRecaudo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Placa", "Marca", "Modelo", "Cilindraje", "Cant Pas", "Valor", "Impuesto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollTblVehiRecaudo.setViewportView(tblDatosVehiRecaudo);

        lblFechaPagoOp.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblFechaPagoOp.setText("Fecha de pago oportuno");

        lblFechaPagoTar.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblFechaPagoTar.setText("Fecha de pago tardio");

        btnAnadirFormulario.setBackground(new java.awt.Color(255, 102, 102));
        btnAnadirFormulario.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        btnAnadirFormulario.setForeground(new java.awt.Color(255, 255, 255));
        btnAnadirFormulario.setText("Añadir Formulario");
        btnAnadirFormulario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAnadirFormulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirFormularioActionPerformed(evt);
            }
        });

        separador.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblDescuentoAdicional.setText("Descuento Adicicional");

        cmbDescuentoAdd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Si", "No" }));
        cmbDescuentoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDescuentoAddActionPerformed(evt);
            }
        });

        lblValDescuentoAdicional.setText("Valor Descuento Adicional");

        lblNFactura.setText("Nº Factura");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTblDatosContRecaudo)
                    .addComponent(lblTblContRecaudo)
                    .addComponent(lblTblVehiRecaudo)
                    .addComponent(btnAnadirFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollTblVehiRecaudo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaPagoOp)
                            .addComponent(lblFechaPagoTar)
                            .addComponent(txtFechaPagoOp, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaPagoTar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNFactura)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNFactura, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbDescuentoAdd, javax.swing.GroupLayout.Alignment.LEADING, 0, 148, Short.MAX_VALUE)
                                    .addComponent(lblDescuentoAdicional, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblValDescuentoAdicional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDescuentoAdicional))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTblVehiRecaudo)
                .addGap(6, 6, 6)
                .addComponent(scrollTblVehiRecaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTblContRecaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(scrollTblDatosContRecaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescuentoAdicional)
                            .addComponent(lblValDescuentoAdicional))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbDescuentoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescuentoAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(lblNFactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblFechaPagoOp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaPagoOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFechaPagoTar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaPagoTar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(separador, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addComponent(btnAnadirFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbDescuentoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDescuentoAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDescuentoAddActionPerformed

    private void btnAnadirFormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirFormularioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnadirFormularioActionPerformed

    /**
     *
     * @return
     */
    public JButton getBtnAnadirFormulario() {
        return btnAnadirFormulario;
    }

    /**
     *
     * @param btnAnadirFormulario
     */
    public void setBtnAnadirFormulario(JButton btnAnadirFormulario) {
        this.btnAnadirFormulario = btnAnadirFormulario;
    }

    /**
     *
     * @return
     */
    public JComboBox<String> getCmbDescuentoAdd() {
        return cmbDescuentoAdd;
    }

    /**
     *
     * @param cmbDescuentoAdd
     */
    public void setCmbDescuentoAdd(JComboBox<String> cmbDescuentoAdd) {
        this.cmbDescuentoAdd = cmbDescuentoAdd;
    }

    /**
     *
     * @return
     */
    public JLabel getLblDescuentoAdicional() {
        return lblDescuentoAdicional;
    }

    /**
     *
     * @param lblDescuentoAdicional
     */
    public void setLblDescuentoAdicional(JLabel lblDescuentoAdicional) {
        this.lblDescuentoAdicional = lblDescuentoAdicional;
    }

    /**
     *
     * @return
     */
    public JLabel getLblFechaPagoOp() {
        return lblFechaPagoOp;
    }

    /**
     *
     * @param lblFechaPagoOp
     */
    public void setLblFechaPagoOp(JLabel lblFechaPagoOp) {
        this.lblFechaPagoOp = lblFechaPagoOp;
    }

    /**
     *
     * @return
     */
    public JLabel getLblFechaPagoTar() {
        return lblFechaPagoTar;
    }

    /**
     *
     * @param lblFechaPagoTar
     */
    public void setLblFechaPagoTar(JLabel lblFechaPagoTar) {
        this.lblFechaPagoTar = lblFechaPagoTar;
    }

    /**
     *
     * @return
     */
    public JLabel getLblNFactura() {
        return lblNFactura;
    }

    /**
     *
     * @param lblNFactura
     */
    public void setLblNFactura(JLabel lblNFactura) {
        this.lblNFactura = lblNFactura;
    }

    /**
     *
     * @return
     */
    public JLabel getLblTblContRecaudo() {
        return lblTblContRecaudo;
    }

    /**
     *
     * @param lblTblContRecaudo
     */
    public void setLblTblContRecaudo(JLabel lblTblContRecaudo) {
        this.lblTblContRecaudo = lblTblContRecaudo;
    }

    /**
     *
     * @return
     */
    public JLabel getLblTblVehiRecaudo() {
        return lblTblVehiRecaudo;
    }

    /**
     *
     * @param lblTblVehiRecaudo
     */
    public void setLblTblVehiRecaudo(JLabel lblTblVehiRecaudo) {
        this.lblTblVehiRecaudo = lblTblVehiRecaudo;
    }

    /**
     *
     * @return
     */
    public JLabel getLblValDescuentoAdicional() {
        return lblValDescuentoAdicional;
    }

    /**
     *
     * @param lblValDescuentoAdicional
     */
    public void setLblValDescuentoAdicional(JLabel lblValDescuentoAdicional) {
        this.lblValDescuentoAdicional = lblValDescuentoAdicional;
    }

    /**
     *
     * @return
     */
    public JScrollPane getScrollTblDatosContRecaudo() {
        return scrollTblDatosContRecaudo;
    }

    /**
     *
     * @param scrollTblDatosContRecaudo
     */
    public void setScrollTblDatosContRecaudo(JScrollPane scrollTblDatosContRecaudo) {
        this.scrollTblDatosContRecaudo = scrollTblDatosContRecaudo;
    }

    /**
     *
     * @return
     */
    public JScrollPane getScrollTblVehiRecaudo() {
        return scrollTblVehiRecaudo;
    }

    /**
     *
     * @param scrollTblVehiRecaudo
     */
    public void setScrollTblVehiRecaudo(JScrollPane scrollTblVehiRecaudo) {
        this.scrollTblVehiRecaudo = scrollTblVehiRecaudo;
    }

    /**
     *
     * @return
     */
    public JSeparator getSeparador() {
        return separador;
    }

    /**
     *
     * @param separador
     */
    public void setSeparador(JSeparator separador) {
        this.separador = separador;
    }

    /**
     *
     * @return
     */
    public JTable getTblDatosContRecaudo() {
        return tblDatosContRecaudo;
    }

    /**
     *
     * @param tblDatosContRecaudo
     */
    public void setTblDatosContRecaudo(JTable tblDatosContRecaudo) {
        this.tblDatosContRecaudo = tblDatosContRecaudo;
    }

    /**
     *
     * @return
     */
    public JTable getTblDatosVehiRecaudo() {
        return tblDatosVehiRecaudo;
    }

    /**
     *
     * @param tblDatosVehiRecaudo
     */
    public void setTblDatosVehiRecaudo(JTable tblDatosVehiRecaudo) {
        this.tblDatosVehiRecaudo = tblDatosVehiRecaudo;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtDescuentoAdicional() {
        return txtDescuentoAdicional;
    }

    /**
     *
     * @param txtDescuentoAdicional
     */
    public void setTxtDescuentoAdicional(JTextField txtDescuentoAdicional) {
        this.txtDescuentoAdicional = txtDescuentoAdicional;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtFechaPagoOp() {
        return txtFechaPagoOp;
    }

    /**
     *
     * @param txtFechaPagoOp
     */
    public void setTxtFechaPagoOp(JTextField txtFechaPagoOp) {
        this.txtFechaPagoOp = txtFechaPagoOp;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtFechaPagoTar() {
        return txtFechaPagoTar;
    }

    /**
     *
     * @param txtFechaPagoTar
     */
    public void setTxtFechaPagoTar(JTextField txtFechaPagoTar) {
        this.txtFechaPagoTar = txtFechaPagoTar;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtNFactura() {
        return txtNFactura;
    }

    /**
     *
     * @param txtNFactura
     */
    public void setTxtNFactura(JTextField txtNFactura) {
        this.txtNFactura = txtNFactura;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadirFormulario;
    private javax.swing.JComboBox<String> cmbDescuentoAdd;
    private javax.swing.JLabel lblDescuentoAdicional;
    private javax.swing.JLabel lblFechaPagoOp;
    private javax.swing.JLabel lblFechaPagoTar;
    private javax.swing.JLabel lblNFactura;
    private javax.swing.JLabel lblTblContRecaudo;
    private javax.swing.JLabel lblTblVehiRecaudo;
    private javax.swing.JLabel lblValDescuentoAdicional;
    private javax.swing.JScrollPane scrollTblDatosContRecaudo;
    private javax.swing.JScrollPane scrollTblVehiRecaudo;
    private javax.swing.JSeparator separador;
    private javax.swing.JTable tblDatosContRecaudo;
    private javax.swing.JTable tblDatosVehiRecaudo;
    private javax.swing.JTextField txtDescuentoAdicional;
    private javax.swing.JTextField txtFechaPagoOp;
    private javax.swing.JTextField txtFechaPagoTar;
    private javax.swing.JTextField txtNFactura;
    // End of variables declaration//GEN-END:variables
}
