/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Dyl
 */
public class IfrmAgVehiculo extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmAgVehiculo
     */
    public IfrmAgVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtModelo = new javax.swing.JTextField();
        lblPlaca = new javax.swing.JLabel();
        btnCambiarVehiculo = new javax.swing.JButton();
        txtMarca = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        lblCilindraje = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblCombustible = new javax.swing.JLabel();
        txtCombustible = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        txtCanPas = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtValor = new javax.swing.JTextField();
        cmbVehiculo = new javax.swing.JComboBox<>();
        txtCilindraje = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        btnRegistrar = new javax.swing.JButton();
        lblModelo = new javax.swing.JLabel();
        lblCantPas = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblTblDatosVehiculo = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        scrollTblDatosVehiculo = new javax.swing.JScrollPane();
        tblDatosVehiculo = new javax.swing.JTable();
        lblUso = new javax.swing.JLabel();
        txtLinea = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txtUso = new javax.swing.JTextField();
        lblLinea = new javax.swing.JLabel();
        lblCapacidad = new javax.swing.JLabel();
        txtGrupo = new javax.swing.JTextField();
        txtCapacidad = new javax.swing.JTextField();
        lblGrupo = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Agregar Vehiculo");

        txtModelo.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });

        lblPlaca.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblPlaca.setText("Placa ");

        btnCambiarVehiculo.setBackground(new java.awt.Color(255, 255, 204));
        btnCambiarVehiculo.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnCambiarVehiculo.setForeground(new java.awt.Color(0, 0, 0));
        btnCambiarVehiculo.setText("CAMBIAR");
        btnCambiarVehiculo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCambiarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarVehiculoActionPerformed(evt);
            }
        });

        txtMarca.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });

        lblTipo.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblTipo.setText("Tipo");

        lblCilindraje.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblCilindraje.setText("Cilindraje");

        lblCombustible.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblCombustible.setText("Combustible");

        txtCombustible.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtCombustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCombustibleActionPerformed(evt);
            }
        });

        txtPlaca.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });

        txtCanPas.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtCanPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCanPasActionPerformed(evt);
            }
        });

        txtValor.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        cmbVehiculo.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        cmbVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Vehiculo", "Carro", "Moto" }));
        cmbVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVehiculoActionPerformed(evt);
            }
        });

        txtCilindraje.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtCilindraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCilindrajeActionPerformed(evt);
            }
        });

        btnRegistrar.setBackground(new java.awt.Color(255, 255, 204));
        btnRegistrar.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lblModelo.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblModelo.setText("Modelo");

        lblCantPas.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblCantPas.setText("Cant pasajeros");

        lblMarca.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblMarca.setText("Marca");

        lblTblDatosVehiculo.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblTblDatosVehiculo.setText("DATOS DE VEHICULO REGISTRADO");

        lblValor.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblValor.setText("Valor");

        tblDatosVehiculo.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tblDatosVehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Placa", "Marca", "Modelo", "Cilindraje", "Cant Pas", "Valor", "Impuesto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollTblDatosVehiculo.setViewportView(tblDatosVehiculo);

        lblUso.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblUso.setText("Uso");

        txtLinea.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLineaActionPerformed(evt);
            }
        });

        txtUso.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsoActionPerformed(evt);
            }
        });

        lblLinea.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblLinea.setText("Linea");

        lblCapacidad.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblCapacidad.setText("Capacidad");

        txtGrupo.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrupoActionPerformed(evt);
            }
        });

        txtCapacidad.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtCapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapacidadActionPerformed(evt);
            }
        });

        lblGrupo.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblGrupo.setText("Grupo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTblDatosVehiculo)
                        .addGap(421, 421, 421))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scrollTblDatosVehiculo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(46, 46, 46)
                                                        .addComponent(lblUso))
                                                    .addComponent(lblValor, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addComponent(lblModelo, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(lblPlaca, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblMarca)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtUso, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblLinea)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblCilindraje)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblCombustible)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jSeparator3)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblCapacidad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblGrupo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jSeparator7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(lblTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbVehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCantPas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCanPas, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCambiarVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPlaca)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMarca)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblModelo)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCilindraje)
                            .addComponent(txtCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValor)
                            .addComponent(lblCombustible)
                            .addComponent(txtCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUso)
                            .addComponent(lblLinea)
                            .addComponent(txtLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCapacidad)
                            .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGrupo)
                            .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipo)
                            .addComponent(cmbVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCantPas)
                            .addComponent(txtCanPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTblDatosVehiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollTblDatosVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCambiarVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void btnCambiarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambiarVehiculoActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void txtCombustibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCombustibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCombustibleActionPerformed

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void cmbVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbVehiculoActionPerformed

    private void txtCilindrajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCilindrajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCilindrajeActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtCanPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCanPasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCanPasActionPerformed

    private void txtLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLineaActionPerformed

    private void txtUsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsoActionPerformed

    private void txtGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrupoActionPerformed

    private void txtCapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacidadActionPerformed

    /**
     *
     * @return
     */
    public JSeparator getjSeparator6() {
        return jSeparator6;
    }

    /**
     *
     * @param jSeparator6
     */
    public void setjSeparator6(JSeparator jSeparator6) {
        this.jSeparator6 = jSeparator6;
    }

    /**
     *
     * @return
     */
    public JSeparator getjSeparator7() {
        return jSeparator7;
    }

    /**
     *
     * @param jSeparator7
     */
    public void setjSeparator7(JSeparator jSeparator7) {
        this.jSeparator7 = jSeparator7;
    }

    /**
     *
     * @return
     */
    public JLabel getLblCapacidad() {
        return lblCapacidad;
    }

    /**
     *
     * @param lblCapacidad
     */
    public void setLblCapacidad(JLabel lblCapacidad) {
        this.lblCapacidad = lblCapacidad;
    }

    /**
     *
     * @return
     */
    public JLabel getLblGrupo() {
        return lblGrupo;
    }

    /**
     *
     * @param lblGrupo
     */
    public void setLblGrupo(JLabel lblGrupo) {
        this.lblGrupo = lblGrupo;
    }

    /**
     *
     * @return
     */
    public JLabel getLblLinea() {
        return lblLinea;
    }

    /**
     *
     * @param lblLinea
     */
    public void setLblLinea(JLabel lblLinea) {
        this.lblLinea = lblLinea;
    }

    /**
     *
     * @return
     */
    public JLabel getLblUso() {
        return lblUso;
    }

    /**
     *
     * @param lblUso
     */
    public void setLblUso(JLabel lblUso) {
        this.lblUso = lblUso;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtCapacidad() {
        return txtCapacidad;
    }

    /**
     *
     * @param txtCapacidad
     */
    public void setTxtCapacidad(JTextField txtCapacidad) {
        this.txtCapacidad = txtCapacidad;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtGrupo() {
        return txtGrupo;
    }

    /**
     *
     * @param txtGrupo
     */
    public void setTxtGrupo(JTextField txtGrupo) {
        this.txtGrupo = txtGrupo;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtLinea() {
        return txtLinea;
    }

    /**
     *
     * @param txtLinea
     */
    public void setTxtLinea(JTextField txtLinea) {
        this.txtLinea = txtLinea;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtUso() {
        return txtUso;
    }

    /**
     *
     * @param txtUso
     */
    public void setTxtUso(JTextField txtUso) {
        this.txtUso = txtUso;
    }

    
    
    /**
     *
     * @return
     */
    public JButton getBtnCambiarVehiculo() {
        return btnCambiarVehiculo;
    }

    /**
     *
     * @param btnCambiarVehiculo
     */
    public void setBtnCambiarVehiculo(JButton btnCambiarVehiculo) {
        this.btnCambiarVehiculo = btnCambiarVehiculo;
    }

    /**
     *
     * @return
     */
    public JButton getBtnRegistrar() {
        return btnRegistrar;
    }

    /**
     *
     * @param btnRegistrar
     */
    public void setBtnRegistrar(JButton btnRegistrar) {
        this.btnRegistrar = btnRegistrar;
    }

    /**
     *
     * @return
     */
    public JComboBox<String> getCmbVehiculo() {
        return cmbVehiculo;
    }

    /**
     *
     * @param cmbVehiculo
     */
    public void setCmbVehiculo(JComboBox<String> cmbVehiculo) {
        this.cmbVehiculo = cmbVehiculo;
    }

    /**
     *
     * @return
     */
    public JSeparator getjSeparator3() {
        return jSeparator3;
    }

    /**
     *
     * @param jSeparator3
     */
    public void setjSeparator3(JSeparator jSeparator3) {
        this.jSeparator3 = jSeparator3;
    }

    /**
     *
     * @return
     */
    public JSeparator getjSeparator4() {
        return jSeparator4;
    }

    /**
     *
     * @param jSeparator4
     */
    public void setjSeparator4(JSeparator jSeparator4) {
        this.jSeparator4 = jSeparator4;
    }

    /**
     *
     * @return
     */
    public JSeparator getjSeparator5() {
        return jSeparator5;
    }

    /**
     *
     * @param jSeparator5
     */
    public void setjSeparator5(JSeparator jSeparator5) {
        this.jSeparator5 = jSeparator5;
    }

    /**
     *
     * @return
     */
    public JLabel getLblCantPas() {
        return lblCantPas;
    }

    /**
     *
     * @param lblCantPas
     */
    public void setLblCantPas(JLabel lblCantPas) {
        this.lblCantPas = lblCantPas;
    }

    /**
     *
     * @return
     */
    public JLabel getLblCilindraje() {
        return lblCilindraje;
    }

    /**
     *
     * @param lblCilindraje
     */
    public void setLblCilindraje(JLabel lblCilindraje) {
        this.lblCilindraje = lblCilindraje;
    }

    /**
     *
     * @return
     */
    public JLabel getLblCombustible() {
        return lblCombustible;
    }

    /**
     *
     * @param lblCombustible
     */
    public void setLblCombustible(JLabel lblCombustible) {
        this.lblCombustible = lblCombustible;
    }

    /**
     *
     * @return
     */
    public JLabel getLblMarca() {
        return lblMarca;
    }

    /**
     *
     * @param lblMarca
     */
    public void setLblMarca(JLabel lblMarca) {
        this.lblMarca = lblMarca;
    }

    /**
     *
     * @return
     */
    public JLabel getLblModelo() {
        return lblModelo;
    }

    /**
     *
     * @param lblModelo
     */
    public void setLblModelo(JLabel lblModelo) {
        this.lblModelo = lblModelo;
    }

    /**
     *
     * @return
     */
    public JLabel getLblPlaca() {
        return lblPlaca;
    }

    /**
     *
     * @param lblPlaca
     */
    public void setLblPlaca(JLabel lblPlaca) {
        this.lblPlaca = lblPlaca;
    }

    /**
     *
     * @return
     */
    public JLabel getLblTblDatosVehiculo() {
        return lblTblDatosVehiculo;
    }

    /**
     *
     * @param lblTblDatosVehiculo
     */
    public void setLblTblDatosVehiculo(JLabel lblTblDatosVehiculo) {
        this.lblTblDatosVehiculo = lblTblDatosVehiculo;
    }

    /**
     *
     * @return
     */
    public JLabel getLblTipo() {
        return lblTipo;
    }

    /**
     *
     * @param lblTipo
     */
    public void setLblTipo(JLabel lblTipo) {
        this.lblTipo = lblTipo;
    }

    /**
     *
     * @return
     */
    public JLabel getLblValor() {
        return lblValor;
    }

    /**
     *
     * @param lblValor
     */
    public void setLblValor(JLabel lblValor) {
        this.lblValor = lblValor;
    }

    /**
     *
     * @return
     */
    public JScrollPane getScrollTblDatosVehiculo() {
        return scrollTblDatosVehiculo;
    }

    /**
     *
     * @param scrollTblDatosVehiculo
     */
    public void setScrollTblDatosVehiculo(JScrollPane scrollTblDatosVehiculo) {
        this.scrollTblDatosVehiculo = scrollTblDatosVehiculo;
    }

    /**
     *
     * @return
     */
    public JTable getTblDatosVehiculo() {
        return tblDatosVehiculo;
    }

    /**
     *
     * @param tblDatosVehiculo
     */
    public void setTblDatosVehiculo(JTable tblDatosVehiculo) {
        this.tblDatosVehiculo = tblDatosVehiculo;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtCanPas() {
        return txtCanPas;
    }

    /**
     *
     * @param txtCanPas
     */
    public void setTxtCanPas(JTextField txtCanPas) {
        this.txtCanPas = txtCanPas;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtCilindraje() {
        return txtCilindraje;
    }

    /**
     *
     * @param txtCilindraje
     */
    public void setTxtCilindraje(JTextField txtCilindraje) {
        this.txtCilindraje = txtCilindraje;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtCombustible() {
        return txtCombustible;
    }

    /**
     *
     * @param txtCombustible
     */
    public void setTxtCombustible(JTextField txtCombustible) {
        this.txtCombustible = txtCombustible;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtMarca() {
        return txtMarca;
    }

    /**
     *
     * @param txtMarca
     */
    public void setTxtMarca(JTextField txtMarca) {
        this.txtMarca = txtMarca;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtModelo() {
        return txtModelo;
    }

    /**
     *
     * @param txtModelo
     */
    public void setTxtModelo(JTextField txtModelo) {
        this.txtModelo = txtModelo;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtPlaca() {
        return txtPlaca;
    }

    /**
     *
     * @param txtPlaca
     */
    public void setTxtPlaca(JTextField txtPlaca) {
        this.txtPlaca = txtPlaca;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtValor() {
        return txtValor;
    }

    /**
     *
     * @param txtValor
     */
    public void setTxtValor(JTextField txtValor) {
        this.txtValor = txtValor;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarVehiculo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbVehiculo;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblCantPas;
    private javax.swing.JLabel lblCapacidad;
    private javax.swing.JLabel lblCilindraje;
    private javax.swing.JLabel lblCombustible;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblLinea;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblTblDatosVehiculo;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblUso;
    private javax.swing.JLabel lblValor;
    private javax.swing.JScrollPane scrollTblDatosVehiculo;
    private javax.swing.JTable tblDatosVehiculo;
    private javax.swing.JTextField txtCanPas;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtCilindraje;
    private javax.swing.JTextField txtCombustible;
    private javax.swing.JTextField txtGrupo;
    private javax.swing.JTextField txtLinea;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtUso;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
