/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author estudiante
 */
public class FrmRegistro extends javax.swing.JFrame {

    /**
     * Creates new form frmVentana
     */
    public FrmRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        tabPaneVehiculo = new javax.swing.JTabbedPane();
        pnlVehiculo = new javax.swing.JPanel();
        txtPlaca = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        txtCilindraje = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        lblValor = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        lblPlaca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblCilindraje = new javax.swing.JLabel();
        lblCantPas = new javax.swing.JLabel();
        txtCanPas = new javax.swing.JTextField();
        cmbVehiculo = new javax.swing.JComboBox<>();
        pnlConsulVehiculo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        btnRecaudo = new javax.swing.JButton();
        txtRecaudo = new javax.swing.JTextField();
        lblRecaudoTotal = new javax.swing.JLabel();
        pnlConsulProp = new javax.swing.JPanel();
        cmbPropietario = new javax.swing.JComboBox<>();
        lblCmbPropietario = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JToggleButton();
        scrPanelTblPropietario = new javax.swing.JScrollPane();
        tblDatosPropietario = new javax.swing.JTable();
        btnRecaudoProp = new javax.swing.JButton();
        lblRecaudoTotalProp = new javax.swing.JLabel();
        lblConsulNombre = new javax.swing.JLabel();
        lblConsulCedula = new javax.swing.JLabel();
        txtRecaudoProp = new javax.swing.JTextField();
        txtConsulNombre = new javax.swing.JTextField();
        txtConsulCedula = new javax.swing.JTextField();
        lblConsulCorreo = new javax.swing.JLabel();
        txtConsulCorreo = new javax.swing.JTextField();
        lblConsulEdad = new javax.swing.JLabel();
        txtConsulEdad = new javax.swing.JTextField();
        pnlProp = new javax.swing.JPanel();
        txtCorreo = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lblFecNac = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtFecNac = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        btnRegistrarProp = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro Impuesto Vehiculo");
        setBackground(new java.awt.Color(153, 204, 0));
        setResizable(false);

        tabPaneVehiculo.setBackground(new java.awt.Color(255, 255, 153));
        tabPaneVehiculo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        pnlVehiculo.setBackground(new java.awt.Color(255, 255, 185));

        txtPlaca.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });

        txtValor.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        txtCilindraje.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        txtCilindraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCilindrajeActionPerformed(evt);
            }
        });

        lblModelo.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        lblModelo.setText("Modelo");

        lblMarca.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        lblMarca.setText("Marca");

        btnRegistrar.setBackground(new java.awt.Color(255, 204, 204));
        btnRegistrar.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lblValor.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        lblValor.setText("Valor");

        txtModelo.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });

        lblPlaca.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        lblPlaca.setText("Placa ");

        txtMarca.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });

        lblCilindraje.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        lblCilindraje.setText("Cilindraje");

        lblCantPas.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        lblCantPas.setText("Cant pasajeros");

        txtCanPas.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        txtCanPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCanPasActionPerformed(evt);
            }
        });

        cmbVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Vehiculo", "Carro", "Moto" }));
        cmbVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlVehiculoLayout = new javax.swing.GroupLayout(pnlVehiculo);
        pnlVehiculo.setLayout(pnlVehiculoLayout);
        pnlVehiculoLayout.setHorizontalGroup(
            pnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVehiculoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVehiculoLayout.createSequentialGroup()
                        .addComponent(cmbVehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCantPas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCanPas, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlVehiculoLayout.createSequentialGroup()
                        .addComponent(lblValor)
                        .addGap(18, 18, 18)
                        .addComponent(txtValor))
                    .addGroup(pnlVehiculoLayout.createSequentialGroup()
                        .addComponent(lblCilindraje)
                        .addGap(18, 18, 18)
                        .addComponent(txtCilindraje, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE))
                    .addGroup(pnlVehiculoLayout.createSequentialGroup()
                        .addGroup(pnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPlaca)
                            .addComponent(lblMarca)
                            .addComponent(lblModelo))
                        .addGap(18, 18, 18)
                        .addGroup(pnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModelo)
                            .addComponent(txtMarca)
                            .addComponent(txtPlaca))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrar)
                .addContainerGap())
        );
        pnlVehiculoLayout.setVerticalGroup(
            pnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlVehiculoLayout.createSequentialGroup()
                        .addGroup(pnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPlaca)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMarca)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblModelo)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCilindraje)
                            .addComponent(txtCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValor)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCantPas)
                            .addComponent(txtCanPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPaneVehiculo.addTab("Vehiculo", pnlVehiculo);

        pnlConsulVehiculo.setBackground(new java.awt.Color(204, 204, 255));

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Placa", "Marca", "Modelo", "Cilindraje", "Cant Pas", "Valor", "Impuesto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDatos);

        btnRecaudo.setText("RECAUDO");

        txtRecaudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecaudoActionPerformed(evt);
            }
        });

        lblRecaudoTotal.setText("Recaudo Total");

        javax.swing.GroupLayout pnlConsulVehiculoLayout = new javax.swing.GroupLayout(pnlConsulVehiculo);
        pnlConsulVehiculo.setLayout(pnlConsulVehiculoLayout);
        pnlConsulVehiculoLayout.setHorizontalGroup(
            pnlConsulVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsulVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConsulVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRecaudo, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(txtRecaudo)
                    .addGroup(pnlConsulVehiculoLayout.createSequentialGroup()
                        .addComponent(lblRecaudoTotal)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlConsulVehiculoLayout.setVerticalGroup(
            pnlConsulVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsulVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConsulVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsulVehiculoLayout.createSequentialGroup()
                        .addComponent(btnRecaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRecaudoTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRecaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPaneVehiculo.addTab("Consulta Recaudo", pnlConsulVehiculo);

        cmbPropietario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Propietario" }));
        cmbPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPropietarioActionPerformed(evt);
            }
        });

        lblCmbPropietario.setText("Propietario");

        btnConsultar.setText("CONSULTAR");

        tblDatosPropietario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Placa", "Marca", "Modelo", "Cilindraje", "Cant Pas", "Valor", "Impuesto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrPanelTblPropietario.setViewportView(tblDatosPropietario);

        btnRecaudoProp.setText("RECAUDO");

        lblRecaudoTotalProp.setText("Recaudo Total");

        lblConsulNombre.setText("Nombre");

        lblConsulCedula.setText("Cedula");

        txtRecaudoProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecaudoPropActionPerformed(evt);
            }
        });

        lblConsulCorreo.setText("Correo");

        txtConsulCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsulCorreoActionPerformed(evt);
            }
        });

        lblConsulEdad.setText("Edad");

        txtConsulEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsulEdadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConsulPropLayout = new javax.swing.GroupLayout(pnlConsulProp);
        pnlConsulProp.setLayout(pnlConsulPropLayout);
        pnlConsulPropLayout.setHorizontalGroup(
            pnlConsulPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsulPropLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConsulPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlConsulPropLayout.createSequentialGroup()
                        .addComponent(lblCmbPropietario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrPanelTblPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlConsulPropLayout.createSequentialGroup()
                        .addGroup(pnlConsulPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblConsulNombre)
                            .addComponent(txtConsulNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlConsulPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConsulCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblConsulCedula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlConsulPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblConsulCorreo)
                            .addComponent(txtConsulCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlConsulPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblConsulEdad)
                            .addComponent(txtConsulEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(12, 12, 12)
                .addGroup(pnlConsulPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsulPropLayout.createSequentialGroup()
                        .addComponent(lblRecaudoTotalProp)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(btnRecaudoProp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRecaudoProp))
                .addContainerGap())
        );
        pnlConsulPropLayout.setVerticalGroup(
            pnlConsulPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsulPropLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConsulPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlConsulPropLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtConsulEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlConsulPropLayout.createSequentialGroup()
                        .addGroup(pnlConsulPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCmbPropietario)
                            .addComponent(btnConsultar))
                        .addGap(12, 12, 12)
                        .addGroup(pnlConsulPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scrPanelTblPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnRecaudoProp, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlConsulPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlConsulPropLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(pnlConsulPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblConsulNombre)
                                    .addComponent(lblConsulCedula)
                                    .addComponent(lblConsulCorreo))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsulPropLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlConsulPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsulPropLayout.createSequentialGroup()
                                        .addGroup(pnlConsulPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblRecaudoTotalProp)
                                            .addComponent(lblConsulEdad))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlConsulPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtRecaudoProp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtConsulNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsulPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtConsulCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtConsulCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );

        tabPaneVehiculo.addTab("Consultar Propietarios", pnlConsulProp);

        pnlProp.setBackground(new java.awt.Color(204, 204, 255));

        txtCorreo.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        lblNombre.setText("Nombre");

        txtCedula.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        lblFecNac.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        lblFecNac.setText("Fecha de Nacimiento");

        txtNom.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        txtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomActionPerformed(evt);
            }
        });

        txtFecNac.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        txtFecNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFecNacActionPerformed(evt);
            }
        });

        lblCorreo.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        lblCorreo.setText("Correo");

        lblCedula.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        lblCedula.setText("Tipo de Documento");

        btnRegistrarProp.setBackground(new java.awt.Color(255, 204, 204));
        btnRegistrarProp.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        btnRegistrarProp.setText("REGISTRAR");
        btnRegistrarProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPropActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", "TI", "TE" }));

        jLabel1.setText("Calidad sobre Vehiculo");

        jLabel2.setText("Direccion");

        jLabel3.setText("Municipio");

        jLabel4.setText("Porcentaje de Propiedad");

        javax.swing.GroupLayout pnlPropLayout = new javax.swing.GroupLayout(pnlProp);
        pnlProp.setLayout(pnlPropLayout);
        pnlPropLayout.setHorizontalGroup(
            pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPropLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNom)
                    .addComponent(lblFecNac)
                    .addComponent(lblCorreo)
                    .addComponent(lblCedula)
                    .addComponent(txtCorreo)
                    .addComponent(lblNombre)
                    .addGroup(pnlPropLayout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFecNac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addGroup(pnlPropLayout.createSequentialGroup()
                        .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 115, Short.MAX_VALUE))
                    .addComponent(jTextField4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarProp)
                .addGap(18, 18, 18))
        );
        pnlPropLayout.setVerticalGroup(
            pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPropLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPropLayout.createSequentialGroup()
                        .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCedula)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCorreo)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFecNac)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFecNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnRegistrarProp, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tabPaneVehiculo.addTab("Propietario", pnlProp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(tabPaneVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPaneVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtCilindrajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCilindrajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCilindrajeActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void cmbVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbVehiculoActionPerformed

    
    private void txtCanPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCanPasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCanPasActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomActionPerformed

    private void txtFecNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFecNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFecNacActionPerformed

    private void btnRegistrarPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarPropActionPerformed

    private void txtRecaudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecaudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecaudoActionPerformed

    private void cmbPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPropietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPropietarioActionPerformed

    private void txtRecaudoPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecaudoPropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecaudoPropActionPerformed

    private void txtConsulCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsulCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsulCorreoActionPerformed

    private void txtConsulEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsulEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsulEdadActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    public JButton getBtnRecaudo() {
        return btnRecaudo;
    }

    public void setBtnRecaudo(JButton btnRecaudo) {
        this.btnRecaudo = btnRecaudo;
    }

    public JButton getBtnRegistrar() {
        return btnRegistrar;
    }

    public void setBtnRegistrar(JButton btnRegistrar) {
        this.btnRegistrar = btnRegistrar;
    }

    public JButton getBtnRegistrarProp() {
        return btnRegistrarProp;
    }

    public void setBtnRegistrarProp(JButton btnRegistrarProp) {
        this.btnRegistrarProp = btnRegistrarProp;
    }

    public JComboBox<String> getCmbVehiculo() {
        return cmbVehiculo;
    }

    public void setCmbVehiculo(JComboBox<String> cmbVehiculo) {
        this.cmbVehiculo = cmbVehiculo;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLblCantPas() {
        return lblCantPas;
    }

    public void setLblCantPas(JLabel lblCantPas) {
        this.lblCantPas = lblCantPas;
    }

    public JLabel getLblCedula() {
        return lblCedula;
    }

    public void setLblCedula(JLabel lblCedula) {
        this.lblCedula = lblCedula;
    }

    public JLabel getLblCilindraje() {
        return lblCilindraje;
    }

    public void setLblCilindraje(JLabel lblCilindraje) {
        this.lblCilindraje = lblCilindraje;
    }

    public JLabel getLblCorreo() {
        return lblCorreo;
    }

    public void setLblCorreo(JLabel lblCorreo) {
        this.lblCorreo = lblCorreo;
    }

    public JLabel getLblFecNac() {
        return lblFecNac;
    }

    public void setLblFecNac(JLabel lblFecNac) {
        this.lblFecNac = lblFecNac;
    }

    public JLabel getLblMarca() {
        return lblMarca;
    }

    public void setLblMarca(JLabel lblMarca) {
        this.lblMarca = lblMarca;
    }

    public JLabel getLblModelo() {
        return lblModelo;
    }

    public void setLblModelo(JLabel lblModelo) {
        this.lblModelo = lblModelo;
    }

    public JLabel getLblNombre() {
        return lblNombre;
    }

    public void setLblNombre(JLabel lblNombre) {
        this.lblNombre = lblNombre;
    }

    public JLabel getLblPlaca() {
        return lblPlaca;
    }

    public void setLblPlaca(JLabel lblPlaca) {
        this.lblPlaca = lblPlaca;
    }

    public JLabel getLblRecaudoTotal() {
        return lblRecaudoTotal;
    }

    public void setLblRecaudoTotal(JLabel lblRecaudoTotal) {
        this.lblRecaudoTotal = lblRecaudoTotal;
    }

    public JLabel getLblValor() {
        return lblValor;
    }

    public void setLblValor(JLabel lblValor) {
        this.lblValor = lblValor;
    }

    public JPanel getPnlConsulVehiculo() {
        return pnlConsulVehiculo;
    }

    public void setPnlConsulVehiculo(JPanel pnlConsulVehiculo) {
        this.pnlConsulVehiculo = pnlConsulVehiculo;
    }

    public JPanel getPnlProp() {
        return pnlProp;
    }

    public void setPnlProp(JPanel pnlProp) {
        this.pnlProp = pnlProp;
    }

    public JPanel getPnlVehiculo() {
        return pnlVehiculo;
    }

    public void setPnlVehiculo(JPanel pnlVehiculo) {
        this.pnlVehiculo = pnlVehiculo;
    }

    public JTabbedPane getTabPaneVehiculo() {
        return tabPaneVehiculo;
    }

    public void setTabPaneVehiculo(JTabbedPane tabPaneVehiculo) {
        this.tabPaneVehiculo = tabPaneVehiculo;
    }

    public JTable getTblDatos() {
        return tblDatos;
    }

    public void setTblDatos(JTable tblDatos) {
        this.tblDatos = tblDatos;
    }

    public JTextField getTxtCanPas() {
        return txtCanPas;
    }

    public void setTxtCanPas(JTextField txtCanPas) {
        this.txtCanPas = txtCanPas;
    }

    public JTextField getTxtCedula() {
        return txtCedula;
    }

    public void setTxtCedula(JTextField txtCedula) {
        this.txtCedula = txtCedula;
    }

    public JTextField getTxtCilindraje() {
        return txtCilindraje;
    }

    public void setTxtCilindraje(JTextField txtCilindraje) {
        this.txtCilindraje = txtCilindraje;
    }

    public JTextField getTxtCorreo() {
        return txtCorreo;
    }

    public void setTxtCorreo(JTextField txtCorreo) {
        this.txtCorreo = txtCorreo;
    }

    public JTextField getTxtFecNac() {
        return txtFecNac;
    }

    public void setTxtFecNac(JTextField txtFecNac) {
        this.txtFecNac = txtFecNac;
    }

    public JTextField getTxtMarca() {
        return txtMarca;
    }

    public void setTxtMarca(JTextField txtMarca) {
        this.txtMarca = txtMarca;
    }

    public JTextField getTxtModelo() {
        return txtModelo;
    }

    public void setTxtModelo(JTextField txtModelo) {
        this.txtModelo = txtModelo;
    }

    public JTextField getTxtNom() {
        return txtNom;
    }

    public void setTxtNom(JTextField txtNom) {
        this.txtNom = txtNom;
    }

    public JTextField getTxtPlaca() {
        return txtPlaca;
    }

    public void setTxtPlaca(JTextField txtPlaca) {
        this.txtPlaca = txtPlaca;
    }

    public JTextField getTxtRecaudo() {
        return txtRecaudo;
    }

    public void setTxtRecaudo(JTextField txtRecaudo) {
        this.txtRecaudo = txtRecaudo;
    }

    public JTextField getTxtValor() {
        return txtValor;
    }

    public void setTxtValor(JTextField txtValor) {
        this.txtValor = txtValor;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnConsultar;
    private javax.swing.JButton btnRecaudo;
    private javax.swing.JButton btnRecaudoProp;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrarProp;
    private javax.swing.JComboBox<String> cmbPropietario;
    private javax.swing.JComboBox<String> cmbVehiculo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblCantPas;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCilindraje;
    private javax.swing.JLabel lblCmbPropietario;
    private javax.swing.JLabel lblConsulCedula;
    private javax.swing.JLabel lblConsulCorreo;
    private javax.swing.JLabel lblConsulEdad;
    private javax.swing.JLabel lblConsulNombre;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblFecNac;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblRecaudoTotal;
    private javax.swing.JLabel lblRecaudoTotalProp;
    private javax.swing.JLabel lblValor;
    private javax.swing.JPanel pnlConsulProp;
    private javax.swing.JPanel pnlConsulVehiculo;
    private javax.swing.JPanel pnlProp;
    private javax.swing.JPanel pnlVehiculo;
    private javax.swing.JScrollPane scrPanelTblPropietario;
    private javax.swing.JTabbedPane tabPaneVehiculo;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTable tblDatosPropietario;
    private javax.swing.JTextField txtCanPas;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCilindraje;
    private javax.swing.JTextField txtConsulCedula;
    private javax.swing.JTextField txtConsulCorreo;
    private javax.swing.JTextField txtConsulEdad;
    private javax.swing.JTextField txtConsulNombre;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtFecNac;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtRecaudo;
    private javax.swing.JTextField txtRecaudoProp;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
