package Vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JToggleButton;
import javax.swing.JToolBar;

/**
 *
 * @author Dyl
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        tbEstado = new javax.swing.JToolBar();
        lblFecha = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        tbBtnSuma = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        tbBtnPotencia = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        tbBtnFecha = new javax.swing.JToggleButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        tbBtnSalir = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        opcSuma = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        opcPotencia = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        opcSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(255, 255, 204));

        tbEstado.setBackground(new java.awt.Color(255, 255, 255));
        tbEstado.setRollover(true);

        lblFecha.setMaximumSize(new java.awt.Dimension(300, 50));
        tbEstado.add(lblFecha);

        escritorio.setLayer(tbEstado, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(tbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jToolBar1.setBackground(new java.awt.Color(255, 204, 204));
        jToolBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator7);

        tbBtnSuma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Suma.png"))); // NOI18N
        tbBtnSuma.setFocusable(false);
        tbBtnSuma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbBtnSuma.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(tbBtnSuma);
        jToolBar1.add(jSeparator4);

        tbBtnPotencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Exponente.png"))); // NOI18N
        tbBtnPotencia.setFocusable(false);
        tbBtnPotencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbBtnPotencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(tbBtnPotencia);
        jToolBar1.add(jSeparator3);

        tbBtnFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/calendario.png"))); // NOI18N
        tbBtnFecha.setFocusable(false);
        tbBtnFecha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbBtnFecha.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(tbBtnFecha);
        jToolBar1.add(jSeparator6);

        tbBtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Salida.png"))); // NOI18N
        tbBtnSalir.setFocusable(false);
        tbBtnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbBtnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(tbBtnSalir);
        jToolBar1.add(jSeparator5);

        jMenu1.setText("Archivos");

        opcSuma.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opcSuma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Suma.png"))); // NOI18N
        opcSuma.setText("Suma");
        jMenu1.add(opcSuma);
        jMenu1.add(jSeparator1);

        opcPotencia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opcPotencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Exponente.png"))); // NOI18N
        opcPotencia.setText("Potencia");
        jMenu1.add(opcPotencia);
        jMenu1.add(jSeparator2);

        opcSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opcSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Salida.png"))); // NOI18N
        opcSalir.setText("Salir");
        jMenu1.add(opcSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JDesktopPane getEscritorio() {
        return escritorio;
    }

    public void setEscritorio(JDesktopPane escritorio) {
        this.escritorio = escritorio;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JPopupMenu.Separator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JPopupMenu.Separator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JPopupMenu.Separator getjSeparator2() {
        return jSeparator2;
    }

    public void setjSeparator2(JPopupMenu.Separator jSeparator2) {
        this.jSeparator2 = jSeparator2;
    }

    public JToolBar.Separator getjSeparator3() {
        return jSeparator3;
    }

    public void setjSeparator3(JToolBar.Separator jSeparator3) {
        this.jSeparator3 = jSeparator3;
    }

    public JToolBar.Separator getjSeparator6() {
        return jSeparator6;
    }

    public void setjSeparator6(JToolBar.Separator jSeparator6) {
        this.jSeparator6 = jSeparator6;
    }

    public JToolBar getjToolBar1() {
        return jToolBar1;
    }

    public void setjToolBar1(JToolBar jToolBar1) {
        this.jToolBar1 = jToolBar1;
    }

    public JLabel getLblFecha() {
        return lblFecha;
    }

    public void setLblFecha(JLabel lblFecha) {
        this.lblFecha = lblFecha;
    }

    public JMenuItem getOpcPotencia() {
        return opcPotencia;
    }

    public void setOpcPotencia(JMenuItem opcPotencia) {
        this.opcPotencia = opcPotencia;
    }

    public JMenuItem getOpcSalir() {
        return opcSalir;
    }

    public void setOpcSalir(JMenuItem opcSalir) {
        this.opcSalir = opcSalir;
    }

    public JMenuItem getOpcSuma() {
        return opcSuma;
    }

    public void setOpcSuma(JMenuItem opcSuma) {
        this.opcSuma = opcSuma;
    }

    public JToggleButton getTbBtnFecha() {
        return tbBtnFecha;
    }

    public void setTbBtnFecha(JToggleButton tbBtnFecha) {
        this.tbBtnFecha = tbBtnFecha;
    }

    public JButton getTbBtnPotencia() {
        return tbBtnPotencia;
    }

    public void setTbBtnPotencia(JButton tbBtnPotencia) {
        this.tbBtnPotencia = tbBtnPotencia;
    }

    public JButton getTbBtnSalir() {
        return tbBtnSalir;
    }

    public void setTbBtnSalir(JButton tbBtnSalir) {
        this.tbBtnSalir = tbBtnSalir;
    }

    public JButton getTbBtnSuma() {
        return tbBtnSuma;
    }

    public void setTbBtnSuma(JButton tbBtnSuma) {
        this.tbBtnSuma = tbBtnSuma;
    }

    public JToolBar getTbEstado() {
        return tbEstado;
    }

    public void setTbEstado(JToolBar tbEstado) {
        this.tbEstado = tbEstado;
    }
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JMenuItem opcPotencia;
    private javax.swing.JMenuItem opcSalir;
    private javax.swing.JMenuItem opcSuma;
    private javax.swing.JToggleButton tbBtnFecha;
    private javax.swing.JButton tbBtnPotencia;
    private javax.swing.JButton tbBtnSalir;
    private javax.swing.JButton tbBtnSuma;
    private javax.swing.JToolBar tbEstado;
    // End of variables declaration//GEN-END:variables

}
