/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JToolBar;

/**
 *
 * @author Estudiante
 */
public class FrmInicio extends javax.swing.JFrame {

    /**
     * Creates new form frmInicio
     */
    public FrmInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnRegistrar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnRecaudo = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnSalir = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        btnRegistrarMenu = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        btnRegPropMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        btnSalirMenu = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        btnRecaudoMenu = new javax.swing.JMenuItem();
        btnConsulPropMenu = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        btnAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator4);

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vehiculo.png"))); // NOI18N
        btnRegistrar.setToolTipText("Registrar Vehiculos (Alt + V)");
        btnRegistrar.setFocusable(false);
        btnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setName(""); // NOI18N
        btnRegistrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnRegistrar);
        jToolBar1.add(jSeparator2);

        btnRecaudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        btnRecaudo.setToolTipText("Consultar recaudo (Alt + R)");
        btnRecaudo.setFocusable(false);
        btnRecaudo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRecaudo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnRecaudo);
        jToolBar1.add(jSeparator3);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salida.png"))); // NOI18N
        btnSalir.setToolTipText("Salir");
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnSalir);
        jToolBar1.add(jSeparator5);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Registrar");
        fileMenu.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        btnRegistrarMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_DOWN_MASK));
        btnRegistrarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vehiculo.png"))); // NOI18N
        btnRegistrarMenu.setMnemonic('o');
        btnRegistrarMenu.setText("Vehiculos");
        fileMenu.add(btnRegistrarMenu);
        fileMenu.add(jSeparator6);

        btnRegPropMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        btnRegPropMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/propietario.png"))); // NOI18N
        btnRegPropMenu.setText("Propietarios");
        fileMenu.add(btnRegPropMenu);
        fileMenu.add(jSeparator1);

        btnSalirMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_DOWN_MASK));
        btnSalirMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salida.png"))); // NOI18N
        btnSalirMenu.setMnemonic('x');
        btnSalirMenu.setText("Salir");
        btnSalirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirMenuActionPerformed(evt);
            }
        });
        fileMenu.add(btnSalirMenu);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Consultar");
        editMenu.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        btnRecaudoMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_DOWN_MASK));
        btnRecaudoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        btnRecaudoMenu.setMnemonic('d');
        btnRecaudoMenu.setText("Recaudo");
        editMenu.add(btnRecaudoMenu);

        btnConsulPropMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        btnConsulPropMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/propietario.png"))); // NOI18N
        btnConsulPropMenu.setText("Propietario");
        editMenu.add(btnConsulPropMenu);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");
        helpMenu.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        btnAcercaDe.setMnemonic('a');
        btnAcercaDe.setText("Acerca de");
        helpMenu.add(btnAcercaDe);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE))
                .addGap(3, 3, 3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirMenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirMenuActionPerformed

    public JMenuItem getBtnAcercaDe() {
        return btnAcercaDe;
    }

    public void setBtnAcercaDe(JMenuItem btnAcercaDe) {
        this.btnAcercaDe = btnAcercaDe;
    }

    public JMenuItem getBtnConsulPropMenu() {
        return btnConsulPropMenu;
    }

    public void setBtnConsulPropMenu(JMenuItem btnConsulPropMenu) {
        this.btnConsulPropMenu = btnConsulPropMenu;
    }

    public JButton getBtnRecaudo() {
        return btnRecaudo;
    }

    public void setBtnRecaudo(JButton btnRecaudo) {
        this.btnRecaudo = btnRecaudo;
    }

    public JMenuItem getBtnRecaudoMenu() {
        return btnRecaudoMenu;
    }

    public void setBtnRecaudoMenu(JMenuItem btnRecaudoMenu) {
        this.btnRecaudoMenu = btnRecaudoMenu;
    }

    public JMenuItem getBtnRegPropMenu() {
        return btnRegPropMenu;
    }

    public void setBtnRegPropMenu(JMenuItem btnRegPropMenu) {
        this.btnRegPropMenu = btnRegPropMenu;
    }

    public JButton getBtnRegistrar() {
        return btnRegistrar;
    }

    public void setBtnRegistrar(JButton btnRegistrar) {
        this.btnRegistrar = btnRegistrar;
    }

    public JMenuItem getBtnRegistrarMenu() {
        return btnRegistrarMenu;
    }

    public void setBtnRegistrarMenu(JMenuItem btnRegistrarMenu) {
        this.btnRegistrarMenu = btnRegistrarMenu;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JButton btnSalir) {
        this.btnSalir = btnSalir;
    }

    public JMenuItem getBtnSalirMenu() {
        return btnSalirMenu;
    }

    public void setBtnSalirMenu(JMenuItem btnSalirMenu) {
        this.btnSalirMenu = btnSalirMenu;
    }

    public JDesktopPane getDesktopPane() {
        return desktopPane;
    }

    public void setDesktopPane(JDesktopPane desktopPane) {
        this.desktopPane = desktopPane;
    }

    public JMenu getEditMenu() {
        return editMenu;
    }

    public void setEditMenu(JMenu editMenu) {
        this.editMenu = editMenu;
    }

    public JMenu getFileMenu() {
        return fileMenu;
    }

    public void setFileMenu(JMenu fileMenu) {
        this.fileMenu = fileMenu;
    }

    public JMenu getHelpMenu() {
        return helpMenu;
    }

    public void setHelpMenu(JMenu helpMenu) {
        this.helpMenu = helpMenu;
    }

    public JPopupMenu.Separator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JPopupMenu.Separator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JToolBar.Separator getjSeparator2() {
        return jSeparator2;
    }

    public void setjSeparator2(JToolBar.Separator jSeparator2) {
        this.jSeparator2 = jSeparator2;
    }

    public JToolBar.Separator getjSeparator3() {
        return jSeparator3;
    }

    public void setjSeparator3(JToolBar.Separator jSeparator3) {
        this.jSeparator3 = jSeparator3;
    }

    public JToolBar.Separator getjSeparator4() {
        return jSeparator4;
    }

    public void setjSeparator4(JToolBar.Separator jSeparator4) {
        this.jSeparator4 = jSeparator4;
    }

    public JToolBar.Separator getjSeparator5() {
        return jSeparator5;
    }

    public void setjSeparator5(JToolBar.Separator jSeparator5) {
        this.jSeparator5 = jSeparator5;
    }

    public JPopupMenu.Separator getjSeparator6() {
        return jSeparator6;
    }

    public void setjSeparator6(JPopupMenu.Separator jSeparator6) {
        this.jSeparator6 = jSeparator6;
    }

    public JToolBar getjToolBar1() {
        return jToolBar1;
    }

    public void setjToolBar1(JToolBar jToolBar1) {
        this.jToolBar1 = jToolBar1;
    }

    public void setMenuBar(JMenuBar menuBar) {
        this.menuBar = menuBar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAcercaDe;
    private javax.swing.JMenuItem btnConsulPropMenu;
    private javax.swing.JButton btnRecaudo;
    private javax.swing.JMenuItem btnRecaudoMenu;
    private javax.swing.JMenuItem btnRegPropMenu;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JMenuItem btnRegistrarMenu;
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenuItem btnSalirMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
