/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author Dyl
 */
public class IntFrmConsulProp extends javax.swing.JInternalFrame {

    /**
     * Creates new form IntFrmConsultar
     */
    public IntFrmConsulProp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblRecaudoTotalProp = new javax.swing.JLabel();
        lblConsulNombre = new javax.swing.JLabel();
        lblConsulCedula = new javax.swing.JLabel();
        txtRecaudoProp = new javax.swing.JTextField();
        txtConsulNombre = new javax.swing.JTextField();
        cmbPropietario = new javax.swing.JComboBox<>();
        txtConsulCedula = new javax.swing.JTextField();
        lblCmbPropietario = new javax.swing.JLabel();
        lblConsulCorreo = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JToggleButton();
        txtConsulCorreo = new javax.swing.JTextField();
        scrPanelTblPropietario = new javax.swing.JScrollPane();
        tblDatosPropietario = new javax.swing.JTable();
        lblConsulEdad = new javax.swing.JLabel();
        txtConsulEdad = new javax.swing.JTextField();
        btnRecaudoProp = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 204));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar Recaudo");

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        lblRecaudoTotalProp.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblRecaudoTotalProp.setText("Recaudo Total");

        lblConsulNombre.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblConsulNombre.setText("Nombre");

        lblConsulCedula.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblConsulCedula.setText("Cedula");

        txtRecaudoProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecaudoPropActionPerformed(evt);
            }
        });

        cmbPropietario.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        cmbPropietario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Propietario" }));
        cmbPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPropietarioActionPerformed(evt);
            }
        });

        lblCmbPropietario.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblCmbPropietario.setText("Propietario");

        lblConsulCorreo.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblConsulCorreo.setText("Correo");

        btnConsultar.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        btnConsultar.setText("CONSULTAR");

        txtConsulCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsulCorreoActionPerformed(evt);
            }
        });

        tblDatosPropietario.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tblDatosPropietario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Placa", "Marca", "Modelo", "Cilindraje", "Cant Pas", "Valor", "Impuesto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrPanelTblPropietario.setViewportView(tblDatosPropietario);

        lblConsulEdad.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblConsulEdad.setText("Edad");

        txtConsulEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsulEdadActionPerformed(evt);
            }
        });

        btnRecaudoProp.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        btnRecaudoProp.setText("RECAUDO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCmbPropietario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrPanelTblPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblConsulNombre)
                            .addComponent(txtConsulNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConsulCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblConsulCedula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblConsulCorreo)
                            .addComponent(txtConsulCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblConsulEdad)
                            .addComponent(txtConsulEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblRecaudoTotalProp)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRecaudoProp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRecaudoProp))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtConsulEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCmbPropietario)
                            .addComponent(btnConsultar))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scrPanelTblPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnRecaudoProp, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblConsulNombre)
                                    .addComponent(lblConsulCedula)
                                    .addComponent(lblConsulCorreo))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblRecaudoTotalProp)
                                            .addComponent(lblConsulEdad))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtRecaudoProp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtConsulNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtConsulCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtConsulCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRecaudoPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecaudoPropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecaudoPropActionPerformed

    private void cmbPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPropietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPropietarioActionPerformed

    private void txtConsulCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsulCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsulCorreoActionPerformed

    private void txtConsulEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsulEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsulEdadActionPerformed

    public JToggleButton getBtnConsultar() {
        return btnConsultar;
    }

    public void setBtnConsultar(JToggleButton btnConsultar) {
        this.btnConsultar = btnConsultar;
    }

    public JButton getBtnRecaudoProp() {
        return btnRecaudoProp;
    }

    public void setBtnRecaudoProp(JButton btnRecaudoProp) {
        this.btnRecaudoProp = btnRecaudoProp;
    }

    public JComboBox<String> getCmbPropietario() {
        return cmbPropietario;
    }

    public void setCmbPropietario(JComboBox<String> cmbPropietario) {
        this.cmbPropietario = cmbPropietario;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JLabel getLblCmbPropietario() {
        return lblCmbPropietario;
    }

    public void setLblCmbPropietario(JLabel lblCmbPropietario) {
        this.lblCmbPropietario = lblCmbPropietario;
    }

    public JLabel getLblConsulCedula() {
        return lblConsulCedula;
    }

    public void setLblConsulCedula(JLabel lblConsulCedula) {
        this.lblConsulCedula = lblConsulCedula;
    }

    public JLabel getLblConsulCorreo() {
        return lblConsulCorreo;
    }

    public void setLblConsulCorreo(JLabel lblConsulCorreo) {
        this.lblConsulCorreo = lblConsulCorreo;
    }

    public JLabel getLblConsulEdad() {
        return lblConsulEdad;
    }

    public void setLblConsulEdad(JLabel lblConsulEdad) {
        this.lblConsulEdad = lblConsulEdad;
    }

    public JLabel getLblConsulNombre() {
        return lblConsulNombre;
    }

    public void setLblConsulNombre(JLabel lblConsulNombre) {
        this.lblConsulNombre = lblConsulNombre;
    }

    public JLabel getLblRecaudoTotalProp() {
        return lblRecaudoTotalProp;
    }

    public void setLblRecaudoTotalProp(JLabel lblRecaudoTotalProp) {
        this.lblRecaudoTotalProp = lblRecaudoTotalProp;
    }

    public JScrollPane getScrPanelTblPropietario() {
        return scrPanelTblPropietario;
    }

    public void setScrPanelTblPropietario(JScrollPane scrPanelTblPropietario) {
        this.scrPanelTblPropietario = scrPanelTblPropietario;
    }

    public JTable getTblDatosPropietario() {
        return tblDatosPropietario;
    }

    public void setTblDatosPropietario(JTable tblDatosPropietario) {
        this.tblDatosPropietario = tblDatosPropietario;
    }

    public JTextField getTxtConsulCedula() {
        return txtConsulCedula;
    }

    public void setTxtConsulCedula(JTextField txtConsulCedula) {
        this.txtConsulCedula = txtConsulCedula;
    }

    public JTextField getTxtConsulCorreo() {
        return txtConsulCorreo;
    }

    public void setTxtConsulCorreo(JTextField txtConsulCorreo) {
        this.txtConsulCorreo = txtConsulCorreo;
    }

    public JTextField getTxtConsulEdad() {
        return txtConsulEdad;
    }

    public void setTxtConsulEdad(JTextField txtConsulEdad) {
        this.txtConsulEdad = txtConsulEdad;
    }

    public JTextField getTxtConsulNombre() {
        return txtConsulNombre;
    }

    public void setTxtConsulNombre(JTextField txtConsulNombre) {
        this.txtConsulNombre = txtConsulNombre;
    }

    public JTextField getTxtRecaudoProp() {
        return txtRecaudoProp;
    }

    public void setTxtRecaudoProp(JTextField txtRecaudoProp) {
        this.txtRecaudoProp = txtRecaudoProp;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnConsultar;
    private javax.swing.JButton btnRecaudoProp;
    private javax.swing.JComboBox<String> cmbPropietario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCmbPropietario;
    private javax.swing.JLabel lblConsulCedula;
    private javax.swing.JLabel lblConsulCorreo;
    private javax.swing.JLabel lblConsulEdad;
    private javax.swing.JLabel lblConsulNombre;
    private javax.swing.JLabel lblRecaudoTotalProp;
    private javax.swing.JScrollPane scrPanelTblPropietario;
    private javax.swing.JTable tblDatosPropietario;
    private javax.swing.JTextField txtConsulCedula;
    private javax.swing.JTextField txtConsulCorreo;
    private javax.swing.JTextField txtConsulEdad;
    private javax.swing.JTextField txtConsulNombre;
    private javax.swing.JTextField txtRecaudoProp;
    // End of variables declaration//GEN-END:variables
}
